/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Aircraftequipmentcode_H_
#define	_Aircraftequipmentcode_H_


#include <asn_application.h>

/* Including external dependencies */
#include "COMNAVapproachequipmentavailable.h"
#include "SSRequipmentavailable.h"
#include "COMNAVequipmentstatus.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Aircraftequipmentcode */
typedef struct Aircraftequipmentcode {
	COMNAVapproachequipmentavailable_t	 cOMNAVapproachequipmentavailable;
	struct Aircraftequipmentcode__cOMNAVequipmentstatus_seqOf {
		A_SEQUENCE_OF(COMNAVequipmentstatus_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *cOMNAVequipmentstatus_seqOf;
	SSRequipmentavailable_t	 sSRequipmentavailable;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Aircraftequipmentcode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Aircraftequipmentcode;

#ifdef __cplusplus
}
#endif

#endif	/* _Aircraftequipmentcode_H_ */
#include <asn_internal.h>
