/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Airportdeparture_H_
#define	_Airportdeparture_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Airport.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Airportdeparture */
typedef Airport_t	 Airportdeparture_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Airportdeparture;
asn_struct_free_f Airportdeparture_free;
asn_struct_print_f Airportdeparture_print;
asn_constr_check_f Airportdeparture_constraint;
ber_type_decoder_f Airportdeparture_decode_ber;
der_type_encoder_f Airportdeparture_encode_der;
xer_type_decoder_f Airportdeparture_decode_xer;
xer_type_encoder_f Airportdeparture_encode_xer;
per_type_decoder_f Airportdeparture_decode_uper;
per_type_encoder_f Airportdeparture_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Airportdeparture_H_ */
#include <asn_internal.h>
