/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Altimeter_H_
#define	_Altimeter_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Altimeterenglish.h"
#include "Altimetermetric.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Altimeter_PR {
	Altimeter_PR_NOTHING,	/* No components present */
	Altimeter_PR_altimeterenglish,
	Altimeter_PR_altimetermetric
} Altimeter_PR;

/* Altimeter */
typedef struct Altimeter {
	Altimeter_PR present;
	union Altimeter_u {
		Altimeterenglish_t	 altimeterenglish;
		Altimetermetric_t	 altimetermetric;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Altimeter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Altimeter;

#ifdef __cplusplus
}
#endif

#endif	/* _Altimeter_H_ */
#include <asn_internal.h>
