/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Altimetermetric_H_
#define	_Altimetermetric_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Altimetermetric */
typedef long	 Altimetermetric_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Altimetermetric;
asn_struct_free_f Altimetermetric_free;
asn_struct_print_f Altimetermetric_print;
asn_constr_check_f Altimetermetric_constraint;
ber_type_decoder_f Altimetermetric_decode_ber;
der_type_encoder_f Altimetermetric_encode_der;
xer_type_decoder_f Altimetermetric_decode_xer;
xer_type_encoder_f Altimetermetric_encode_xer;
per_type_decoder_f Altimetermetric_decode_uper;
per_type_encoder_f Altimetermetric_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Altimetermetric_H_ */
#include <asn_internal.h>
