/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_ATCdownlinkmsgelementid_H_
#define	_ATCdownlinkmsgelementid_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DM0NULL.h"
#include "DM1NULL.h"
#include "DM2NULL.h"
#include "DM3NULL.h"
#include "DM4NULL.h"
#include "DM5NULL.h"
#include "DM6Altitude.h"
#include "DM7AltitudeAltitude.h"
#include "DM8Altitude.h"
#include "DM9Altitude.h"
#include "DM10Altitude.h"
#include "DM11PositionAltitude.h"
#include "DM12PositionAltitude.h"
#include "DM13TimeAltitude.h"
#include "DM14TimeAltitude.h"
#include "DM15DistanceoffsetDirection.h"
#include "DM16PositionDistanceoffsetDirection.h"
#include "DM17TimeDistanceoffsetDirection.h"
#include "DM18Speed.h"
#include "DM19SpeedSpeed.h"
#include "DM20NULL.h"
#include "DM21Frequency.h"
#include "DM22Position.h"
#include "DM23Procedurename.h"
#include "DM24Routeclearance.h"
#include "DM25NULL.h"
#include "DM26PositionRouteclearance.h"
#include "DM27DistanceoffsetDirection.h"
#include "DM28Altitude.h"
#include "DM29Altitude.h"
#include "DM30Altitude.h"
#include "DM31Position.h"
#include "DM32Altitude.h"
#include "DM33Position.h"
#include "DM34Speed.h"
#include "DM35Degrees.h"
#include "DM36Degrees.h"
#include "DM37Altitude.h"
#include "DM38Altitude.h"
#include "DM39Speed.h"
#include "DM40Routeclearance.h"
#include "DM41NULL.h"
#include "DM42Position.h"
#include "DM43Time.h"
#include "DM44Position.h"
#include "DM45Position.h"
#include "DM46Time.h"
#include "DM47Beaconcode.h"
#include "DM48Positionreport.h"
#include "DM49Speed.h"
#include "DM50SpeedSpeed.h"
#include "DM51NULL.h"
#include "DM52NULL.h"
#include "DM53NULL.h"
#include "DM54Altitude.h"
#include "DM55NULL.h"
#include "DM56NULL.h"
#include "DM57RemainingfuelRemainingsouls.h"
#include "DM58NULL.h"
#include "DM59PositionRouteclearance.h"
#include "DM60DistanceoffsetDirection.h"
#include "DM61Altitude.h"
#include "DM62Errorinformation.h"
#include "DM63NULL.h"
#include "DM64ICAOfacilitydesignation.h"
#include "DM65NULL.h"
#include "DM66NULL.h"
#include "DM67Freetext.h"
#include "DM68Freetext.h"
#include "DM69NULL.h"
#include "DM70Degrees.h"
#include "DM71Degrees.h"
#include "DM72Altitude.h"
#include "DM73Versionnumber.h"
#include "DM74NULL.h"
#include "DM75NULL.h"
#include "DM76AltitudeAltitude.h"
#include "DM77AltitudeAltitude.h"
#include "DM78TimeDistanceTofromPosition.h"
#include "DM79Atiscode.h"
#include "DM80DistanceoffsetDirection.h"
#include "DM81NULL.h"
#include "DM82NULL.h"
#include "DM83NULL.h"
#include "DM84NULL.h"
#include "DM85NULL.h"
#include "DM86NULL.h"
#include "DM87NULL.h"
#include "DM88NULL.h"
#include "DM89NULL.h"
#include "DM90NULL.h"
#include "DM91NULL.h"
#include "DM92NULL.h"
#include "DM93NULL.h"
#include "DM94NULL.h"
#include "DM95NULL.h"
#include "DM96NULL.h"
#include "DM97NULL.h"
#include "DM98NULL.h"
#include "DM99NULL.h"
#include "DM100NULL.h"
#include "DM101NULL.h"
#include "DM102NULL.h"
#include "DM103NULL.h"
#include "DM104NULL.h"
#include "DM105NULL.h"
#include "DM106NULL.h"
#include "DM107NULL.h"
#include "DM108NULL.h"
#include "DM109NULL.h"
#include "DM110NULL.h"
#include "DM111NULL.h"
#include "DM112NULL.h"
#include "DM113NULL.h"
#include "DM114NULL.h"
#include "DM115NULL.h"
#include "DM116NULL.h"
#include "DM117NULL.h"
#include "DM118NULL.h"
#include "DM119NULL.h"
#include "DM120NULL.h"
#include "DM121NULL.h"
#include "DM122NULL.h"
#include "DM123NULL.h"
#include "DM124NULL.h"
#include "DM125NULL.h"
#include "DM126NULL.h"
#include "DM127NULL.h"
#include "DM128NULL.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ATCdownlinkmsgelementid_PR {
	ATCdownlinkmsgelementid_PR_NOTHING,	/* No components present */
	ATCdownlinkmsgelementid_PR_dM0NULL,
	ATCdownlinkmsgelementid_PR_dM1NULL,
	ATCdownlinkmsgelementid_PR_dM2NULL,
	ATCdownlinkmsgelementid_PR_dM3NULL,
	ATCdownlinkmsgelementid_PR_dM4NULL,
	ATCdownlinkmsgelementid_PR_dM5NULL,
	ATCdownlinkmsgelementid_PR_dM6Altitude,
	ATCdownlinkmsgelementid_PR_dM7AltitudeAltitude,
	ATCdownlinkmsgelementid_PR_dM8Altitude,
	ATCdownlinkmsgelementid_PR_dM9Altitude,
	ATCdownlinkmsgelementid_PR_dM10Altitude,
	ATCdownlinkmsgelementid_PR_dM11PositionAltitude,
	ATCdownlinkmsgelementid_PR_dM12PositionAltitude,
	ATCdownlinkmsgelementid_PR_dM13TimeAltitude,
	ATCdownlinkmsgelementid_PR_dM14TimeAltitude,
	ATCdownlinkmsgelementid_PR_dM15DistanceoffsetDirection,
	ATCdownlinkmsgelementid_PR_dM16PositionDistanceoffsetDirection,
	ATCdownlinkmsgelementid_PR_dM17TimeDistanceoffsetDirection,
	ATCdownlinkmsgelementid_PR_dM18Speed,
	ATCdownlinkmsgelementid_PR_dM19SpeedSpeed,
	ATCdownlinkmsgelementid_PR_dM20NULL,
	ATCdownlinkmsgelementid_PR_dM21Frequency,
	ATCdownlinkmsgelementid_PR_dM22Position,
	ATCdownlinkmsgelementid_PR_dM23Procedurename,
	ATCdownlinkmsgelementid_PR_dM24Routeclearance,
	ATCdownlinkmsgelementid_PR_dM25NULL,
	ATCdownlinkmsgelementid_PR_dM26PositionRouteclearance,
	ATCdownlinkmsgelementid_PR_dM27DistanceoffsetDirection,
	ATCdownlinkmsgelementid_PR_dM28Altitude,
	ATCdownlinkmsgelementid_PR_dM29Altitude,
	ATCdownlinkmsgelementid_PR_dM30Altitude,
	ATCdownlinkmsgelementid_PR_dM31Position,
	ATCdownlinkmsgelementid_PR_dM32Altitude,
	ATCdownlinkmsgelementid_PR_dM33Position,
	ATCdownlinkmsgelementid_PR_dM34Speed,
	ATCdownlinkmsgelementid_PR_dM35Degrees,
	ATCdownlinkmsgelementid_PR_dM36Degrees,
	ATCdownlinkmsgelementid_PR_dM37Altitude,
	ATCdownlinkmsgelementid_PR_dM38Altitude,
	ATCdownlinkmsgelementid_PR_dM39Speed,
	ATCdownlinkmsgelementid_PR_dM40Routeclearance,
	ATCdownlinkmsgelementid_PR_dM41NULL,
	ATCdownlinkmsgelementid_PR_dM42Position,
	ATCdownlinkmsgelementid_PR_dM43Time,
	ATCdownlinkmsgelementid_PR_dM44Position,
	ATCdownlinkmsgelementid_PR_dM45Position,
	ATCdownlinkmsgelementid_PR_dM46Time,
	ATCdownlinkmsgelementid_PR_dM47Beaconcode,
	ATCdownlinkmsgelementid_PR_dM48Positionreport,
	ATCdownlinkmsgelementid_PR_dM49Speed,
	ATCdownlinkmsgelementid_PR_dM50SpeedSpeed,
	ATCdownlinkmsgelementid_PR_dM51NULL,
	ATCdownlinkmsgelementid_PR_dM52NULL,
	ATCdownlinkmsgelementid_PR_dM53NULL,
	ATCdownlinkmsgelementid_PR_dM54Altitude,
	ATCdownlinkmsgelementid_PR_dM55NULL,
	ATCdownlinkmsgelementid_PR_dM56NULL,
	ATCdownlinkmsgelementid_PR_dM57RemainingfuelRemainingsouls,
	ATCdownlinkmsgelementid_PR_dM58NULL,
	ATCdownlinkmsgelementid_PR_dM59PositionRouteclearance,
	ATCdownlinkmsgelementid_PR_dM60DistanceoffsetDirection,
	ATCdownlinkmsgelementid_PR_dM61Altitude,
	ATCdownlinkmsgelementid_PR_dM62Errorinformation,
	ATCdownlinkmsgelementid_PR_dM63NULL,
	ATCdownlinkmsgelementid_PR_dM64ICAOfacilitydesignation,
	ATCdownlinkmsgelementid_PR_dM65NULL,
	ATCdownlinkmsgelementid_PR_dM66NULL,
	ATCdownlinkmsgelementid_PR_dM67Freetext,
	ATCdownlinkmsgelementid_PR_dM68Freetext,
	ATCdownlinkmsgelementid_PR_dM69NULL,
	ATCdownlinkmsgelementid_PR_dM70Degrees,
	ATCdownlinkmsgelementid_PR_dM71Degrees,
	ATCdownlinkmsgelementid_PR_dM72Altitude,
	ATCdownlinkmsgelementid_PR_dM73Versionnumber,
	ATCdownlinkmsgelementid_PR_dM74NULL,
	ATCdownlinkmsgelementid_PR_dM75NULL,
	ATCdownlinkmsgelementid_PR_dM76AltitudeAltitude,
	ATCdownlinkmsgelementid_PR_dM77AltitudeAltitude,
	ATCdownlinkmsgelementid_PR_dM78TimeDistanceTofromPosition,
	ATCdownlinkmsgelementid_PR_dM79Atiscode,
	ATCdownlinkmsgelementid_PR_dM80DistanceoffsetDirection,
	ATCdownlinkmsgelementid_PR_dM81NULL,
	ATCdownlinkmsgelementid_PR_dM82NULL,
	ATCdownlinkmsgelementid_PR_dM83NULL,
	ATCdownlinkmsgelementid_PR_dM84NULL,
	ATCdownlinkmsgelementid_PR_dM85NULL,
	ATCdownlinkmsgelementid_PR_dM86NULL,
	ATCdownlinkmsgelementid_PR_dM87NULL,
	ATCdownlinkmsgelementid_PR_dM88NULL,
	ATCdownlinkmsgelementid_PR_dM89NULL,
	ATCdownlinkmsgelementid_PR_dM90NULL,
	ATCdownlinkmsgelementid_PR_dM91NULL,
	ATCdownlinkmsgelementid_PR_dM92NULL,
	ATCdownlinkmsgelementid_PR_dM93NULL,
	ATCdownlinkmsgelementid_PR_dM94NULL,
	ATCdownlinkmsgelementid_PR_dM95NULL,
	ATCdownlinkmsgelementid_PR_dM96NULL,
	ATCdownlinkmsgelementid_PR_dM97NULL,
	ATCdownlinkmsgelementid_PR_dM98NULL,
	ATCdownlinkmsgelementid_PR_dM99NULL,
	ATCdownlinkmsgelementid_PR_dM100NULL,
	ATCdownlinkmsgelementid_PR_dM101NULL,
	ATCdownlinkmsgelementid_PR_dM102NULL,
	ATCdownlinkmsgelementid_PR_dM103NULL,
	ATCdownlinkmsgelementid_PR_dM104NULL,
	ATCdownlinkmsgelementid_PR_dM105NULL,
	ATCdownlinkmsgelementid_PR_dM106NULL,
	ATCdownlinkmsgelementid_PR_dM107NULL,
	ATCdownlinkmsgelementid_PR_dM108NULL,
	ATCdownlinkmsgelementid_PR_dM109NULL,
	ATCdownlinkmsgelementid_PR_dM110NULL,
	ATCdownlinkmsgelementid_PR_dM111NULL,
	ATCdownlinkmsgelementid_PR_dM112NULL,
	ATCdownlinkmsgelementid_PR_dM113NULL,
	ATCdownlinkmsgelementid_PR_dM114NULL,
	ATCdownlinkmsgelementid_PR_dM115NULL,
	ATCdownlinkmsgelementid_PR_dM116NULL,
	ATCdownlinkmsgelementid_PR_dM117NULL,
	ATCdownlinkmsgelementid_PR_dM118NULL,
	ATCdownlinkmsgelementid_PR_dM119NULL,
	ATCdownlinkmsgelementid_PR_dM120NULL,
	ATCdownlinkmsgelementid_PR_dM121NULL,
	ATCdownlinkmsgelementid_PR_dM122NULL,
	ATCdownlinkmsgelementid_PR_dM123NULL,
	ATCdownlinkmsgelementid_PR_dM124NULL,
	ATCdownlinkmsgelementid_PR_dM125NULL,
	ATCdownlinkmsgelementid_PR_dM126NULL,
	ATCdownlinkmsgelementid_PR_dM127NULL,
	ATCdownlinkmsgelementid_PR_dM128NULL
} ATCdownlinkmsgelementid_PR;

/* ATCdownlinkmsgelementid */
typedef struct ATCdownlinkmsgelementid {
	ATCdownlinkmsgelementid_PR present;
	union ATCdownlinkmsgelementid_u {
		DM0NULL_t	 dM0NULL;
		DM1NULL_t	 dM1NULL;
		DM2NULL_t	 dM2NULL;
		DM3NULL_t	 dM3NULL;
		DM4NULL_t	 dM4NULL;
		DM5NULL_t	 dM5NULL;
		DM6Altitude_t	 dM6Altitude;
		DM7AltitudeAltitude_t	 dM7AltitudeAltitude;
		DM8Altitude_t	 dM8Altitude;
		DM9Altitude_t	 dM9Altitude;
		DM10Altitude_t	 dM10Altitude;
		DM11PositionAltitude_t	 dM11PositionAltitude;
		DM12PositionAltitude_t	 dM12PositionAltitude;
		DM13TimeAltitude_t	 dM13TimeAltitude;
		DM14TimeAltitude_t	 dM14TimeAltitude;
		DM15DistanceoffsetDirection_t	 dM15DistanceoffsetDirection;
		DM16PositionDistanceoffsetDirection_t	 dM16PositionDistanceoffsetDirection;
		DM17TimeDistanceoffsetDirection_t	 dM17TimeDistanceoffsetDirection;
		DM18Speed_t	 dM18Speed;
		DM19SpeedSpeed_t	 dM19SpeedSpeed;
		DM20NULL_t	 dM20NULL;
		DM21Frequency_t	 dM21Frequency;
		DM22Position_t	 dM22Position;
		DM23Procedurename_t	 dM23Procedurename;
		DM24Routeclearance_t	 dM24Routeclearance;
		DM25NULL_t	 dM25NULL;
		DM26PositionRouteclearance_t	 dM26PositionRouteclearance;
		DM27DistanceoffsetDirection_t	 dM27DistanceoffsetDirection;
		DM28Altitude_t	 dM28Altitude;
		DM29Altitude_t	 dM29Altitude;
		DM30Altitude_t	 dM30Altitude;
		DM31Position_t	 dM31Position;
		DM32Altitude_t	 dM32Altitude;
		DM33Position_t	 dM33Position;
		DM34Speed_t	 dM34Speed;
		DM35Degrees_t	 dM35Degrees;
		DM36Degrees_t	 dM36Degrees;
		DM37Altitude_t	 dM37Altitude;
		DM38Altitude_t	 dM38Altitude;
		DM39Speed_t	 dM39Speed;
		DM40Routeclearance_t	 dM40Routeclearance;
		DM41NULL_t	 dM41NULL;
		DM42Position_t	 dM42Position;
		DM43Time_t	 dM43Time;
		DM44Position_t	 dM44Position;
		DM45Position_t	 dM45Position;
		DM46Time_t	 dM46Time;
		DM47Beaconcode_t	 dM47Beaconcode;
		DM48Positionreport_t	 dM48Positionreport;
		DM49Speed_t	 dM49Speed;
		DM50SpeedSpeed_t	 dM50SpeedSpeed;
		DM51NULL_t	 dM51NULL;
		DM52NULL_t	 dM52NULL;
		DM53NULL_t	 dM53NULL;
		DM54Altitude_t	 dM54Altitude;
		DM55NULL_t	 dM55NULL;
		DM56NULL_t	 dM56NULL;
		DM57RemainingfuelRemainingsouls_t	 dM57RemainingfuelRemainingsouls;
		DM58NULL_t	 dM58NULL;
		DM59PositionRouteclearance_t	 dM59PositionRouteclearance;
		DM60DistanceoffsetDirection_t	 dM60DistanceoffsetDirection;
		DM61Altitude_t	 dM61Altitude;
		DM62Errorinformation_t	 dM62Errorinformation;
		DM63NULL_t	 dM63NULL;
		DM64ICAOfacilitydesignation_t	 dM64ICAOfacilitydesignation;
		DM65NULL_t	 dM65NULL;
		DM66NULL_t	 dM66NULL;
		DM67Freetext_t	 dM67Freetext;
		DM68Freetext_t	 dM68Freetext;
		DM69NULL_t	 dM69NULL;
		DM70Degrees_t	 dM70Degrees;
		DM71Degrees_t	 dM71Degrees;
		DM72Altitude_t	 dM72Altitude;
		DM73Versionnumber_t	 dM73Versionnumber;
		DM74NULL_t	 dM74NULL;
		DM75NULL_t	 dM75NULL;
		DM76AltitudeAltitude_t	 dM76AltitudeAltitude;
		DM77AltitudeAltitude_t	 dM77AltitudeAltitude;
		DM78TimeDistanceTofromPosition_t	 dM78TimeDistanceTofromPosition;
		DM79Atiscode_t	 dM79Atiscode;
		DM80DistanceoffsetDirection_t	 dM80DistanceoffsetDirection;
		DM81NULL_t	 dM81NULL;
		DM82NULL_t	 dM82NULL;
		DM83NULL_t	 dM83NULL;
		DM84NULL_t	 dM84NULL;
		DM85NULL_t	 dM85NULL;
		DM86NULL_t	 dM86NULL;
		DM87NULL_t	 dM87NULL;
		DM88NULL_t	 dM88NULL;
		DM89NULL_t	 dM89NULL;
		DM90NULL_t	 dM90NULL;
		DM91NULL_t	 dM91NULL;
		DM92NULL_t	 dM92NULL;
		DM93NULL_t	 dM93NULL;
		DM94NULL_t	 dM94NULL;
		DM95NULL_t	 dM95NULL;
		DM96NULL_t	 dM96NULL;
		DM97NULL_t	 dM97NULL;
		DM98NULL_t	 dM98NULL;
		DM99NULL_t	 dM99NULL;
		DM100NULL_t	 dM100NULL;
		DM101NULL_t	 dM101NULL;
		DM102NULL_t	 dM102NULL;
		DM103NULL_t	 dM103NULL;
		DM104NULL_t	 dM104NULL;
		DM105NULL_t	 dM105NULL;
		DM106NULL_t	 dM106NULL;
		DM107NULL_t	 dM107NULL;
		DM108NULL_t	 dM108NULL;
		DM109NULL_t	 dM109NULL;
		DM110NULL_t	 dM110NULL;
		DM111NULL_t	 dM111NULL;
		DM112NULL_t	 dM112NULL;
		DM113NULL_t	 dM113NULL;
		DM114NULL_t	 dM114NULL;
		DM115NULL_t	 dM115NULL;
		DM116NULL_t	 dM116NULL;
		DM117NULL_t	 dM117NULL;
		DM118NULL_t	 dM118NULL;
		DM119NULL_t	 dM119NULL;
		DM120NULL_t	 dM120NULL;
		DM121NULL_t	 dM121NULL;
		DM122NULL_t	 dM122NULL;
		DM123NULL_t	 dM123NULL;
		DM124NULL_t	 dM124NULL;
		DM125NULL_t	 dM125NULL;
		DM126NULL_t	 dM126NULL;
		DM127NULL_t	 dM127NULL;
		DM128NULL_t	 dM128NULL;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ATCdownlinkmsgelementid_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ATCdownlinkmsgelementid;

#ifdef __cplusplus
}
#endif

#endif	/* _ATCdownlinkmsgelementid_H_ */
#include <asn_internal.h>
