/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_ATCdownlinkmessage_H_
#define	_ATCdownlinkmessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ATCmessageheader.h"
#include "ATCdownlinkmsgelementid.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ATCdownlinkmsgelementid;

/* ATCdownlinkmessage */
typedef struct ATCdownlinkmessage {
	ATCmessageheader_t	 aTCmessageheader;
	ATCdownlinkmsgelementid_t	 aTCdownlinkmsgelementid;
	struct ATCdownlinkmessage__aTCdownlinkmsgelementid_seqOf {
		A_SEQUENCE_OF(struct ATCdownlinkmsgelementid) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *aTCdownlinkmsgelementid_seqOf;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ATCdownlinkmessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ATCdownlinkmessage;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ATCdownlinkmsgelementid.h"

#endif	/* _ATCdownlinkmessage_H_ */
#include <asn_internal.h>
