/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#include "ATCuplinkmsgelementid.h"

static asn_per_constraints_t asn_PER_type_ATCuplinkmsgelementid_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  182 }	/* (0..182) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ATCuplinkmsgelementid_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM0NULL),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM0NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM0NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM1NULL),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM1NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM1NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM2NULL),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM2NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM2NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM3NULL),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM3NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM3NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM4NULL),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM4NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM4NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM5NULL),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM5NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM5NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM6Altitude),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM6Altitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM6Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM7Time),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM7Time,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM7Time"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM8Position),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM8Position,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM8Position"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM9Time),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM9Time,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM9Time"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM10Position),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM10Position,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM10Position"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM11Time),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM11Time,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM11Time"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM12Position),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM12Position,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM12Position"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM13TimeAltitude),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM13TimeAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM13TimeAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM14PositionAltitude),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM14PositionAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM14PositionAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM15TimeAltitude),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM15TimeAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM15TimeAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM16PositionAltitude),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM16PositionAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM16PositionAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM17TimeAltitude),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM17TimeAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM17TimeAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM18PositionAltitude),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM18PositionAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM18PositionAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM19Altitude),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM19Altitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM19Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM20Altitude),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM20Altitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM20Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM21TimeAltitude),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM21TimeAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM21TimeAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM22PositionAltitude),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM22PositionAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM22PositionAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM23Altitude),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM23Altitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM23Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM24TimeAltitude),
		(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM24TimeAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM24TimeAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM25PositionAltitude),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM25PositionAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM25PositionAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM26AltitudeTime),
		(ASN_TAG_CLASS_CONTEXT | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM26AltitudeTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM26AltitudeTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM27AltitudePosition),
		(ASN_TAG_CLASS_CONTEXT | (27 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM27AltitudePosition,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM27AltitudePosition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM28AltitudeTime),
		(ASN_TAG_CLASS_CONTEXT | (28 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM28AltitudeTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM28AltitudeTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM29AltitudePosition),
		(ASN_TAG_CLASS_CONTEXT | (29 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM29AltitudePosition,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM29AltitudePosition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM30AltitudeAltitude),
		(ASN_TAG_CLASS_CONTEXT | (30 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM30AltitudeAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM30AltitudeAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM31AltitudeAltitude),
		(ASN_TAG_CLASS_CONTEXT | (31 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM31AltitudeAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM31AltitudeAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM32AltitudeAltitude),
		(ASN_TAG_CLASS_CONTEXT | (32 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM32AltitudeAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM32AltitudeAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM33Altitude),
		(ASN_TAG_CLASS_CONTEXT | (33 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM33Altitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM33Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM34Altitude),
		(ASN_TAG_CLASS_CONTEXT | (34 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM34Altitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM34Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM35Altitude),
		(ASN_TAG_CLASS_CONTEXT | (35 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM35Altitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM35Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM36Altitude),
		(ASN_TAG_CLASS_CONTEXT | (36 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM36Altitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM36Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM37Altitude),
		(ASN_TAG_CLASS_CONTEXT | (37 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM37Altitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM37Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM38Altitude),
		(ASN_TAG_CLASS_CONTEXT | (38 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM38Altitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM38Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM39Altitude),
		(ASN_TAG_CLASS_CONTEXT | (39 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM39Altitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM39Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM40Altitude),
		(ASN_TAG_CLASS_CONTEXT | (40 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM40Altitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM40Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM41Altitude),
		(ASN_TAG_CLASS_CONTEXT | (41 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM41Altitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM41Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM42PositionAltitude),
		(ASN_TAG_CLASS_CONTEXT | (42 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM42PositionAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM42PositionAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM43PositionAltitude),
		(ASN_TAG_CLASS_CONTEXT | (43 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM43PositionAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM43PositionAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM44PositionAltitude),
		(ASN_TAG_CLASS_CONTEXT | (44 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM44PositionAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM44PositionAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM45PositionAltitude),
		(ASN_TAG_CLASS_CONTEXT | (45 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM45PositionAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM45PositionAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM46PositionAltitude),
		(ASN_TAG_CLASS_CONTEXT | (46 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM46PositionAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM46PositionAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM47PositionAltitude),
		(ASN_TAG_CLASS_CONTEXT | (47 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM47PositionAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM47PositionAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM48PositionAltitude),
		(ASN_TAG_CLASS_CONTEXT | (48 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM48PositionAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM48PositionAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM49PositionAltitude),
		(ASN_TAG_CLASS_CONTEXT | (49 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM49PositionAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM49PositionAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM50PositionAltitudeAltitude),
		(ASN_TAG_CLASS_CONTEXT | (50 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM50PositionAltitudeAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM50PositionAltitudeAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM51PositionTime),
		(ASN_TAG_CLASS_CONTEXT | (51 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM51PositionTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM51PositionTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM52PositionTime),
		(ASN_TAG_CLASS_CONTEXT | (52 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM52PositionTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM52PositionTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM53PositionTime),
		(ASN_TAG_CLASS_CONTEXT | (53 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM53PositionTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM53PositionTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM54PositionTimeTime),
		(ASN_TAG_CLASS_CONTEXT | (54 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM54PositionTimeTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM54PositionTimeTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM55PositionSpeed),
		(ASN_TAG_CLASS_CONTEXT | (55 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM55PositionSpeed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM55PositionSpeed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM56PositionSpeed),
		(ASN_TAG_CLASS_CONTEXT | (56 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM56PositionSpeed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM56PositionSpeed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM57PositionSpeed),
		(ASN_TAG_CLASS_CONTEXT | (57 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM57PositionSpeed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM57PositionSpeed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM58PositionTimeAltitude),
		(ASN_TAG_CLASS_CONTEXT | (58 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM58PositionTimeAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM58PositionTimeAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM59PositionTimeAltitude),
		(ASN_TAG_CLASS_CONTEXT | (59 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM59PositionTimeAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM59PositionTimeAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM60PositionTimeAltitude),
		(ASN_TAG_CLASS_CONTEXT | (60 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM60PositionTimeAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM60PositionTimeAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM61PositionAltitudeSpeed),
		(ASN_TAG_CLASS_CONTEXT | (61 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM61PositionAltitudeSpeed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM61PositionAltitudeSpeed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM62TimePositionAltitude),
		(ASN_TAG_CLASS_CONTEXT | (62 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM62TimePositionAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM62TimePositionAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM63TimePositionAltitudeSpeed),
		(ASN_TAG_CLASS_CONTEXT | (63 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM63TimePositionAltitudeSpeed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM63TimePositionAltitudeSpeed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM64DistanceoffsetDirection),
		(ASN_TAG_CLASS_CONTEXT | (64 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM64DistanceoffsetDirection,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM64DistanceoffsetDirection"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM65PositionDistanceoffsetDirection),
		(ASN_TAG_CLASS_CONTEXT | (65 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM65PositionDistanceoffsetDirection,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM65PositionDistanceoffsetDirection"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM66TimeDistanceoffsetDirection),
		(ASN_TAG_CLASS_CONTEXT | (66 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM66TimeDistanceoffsetDirection,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM66TimeDistanceoffsetDirection"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM67NULL),
		(ASN_TAG_CLASS_CONTEXT | (67 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM67NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM67NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM68Position),
		(ASN_TAG_CLASS_CONTEXT | (68 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM68Position,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM68Position"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM69Time),
		(ASN_TAG_CLASS_CONTEXT | (69 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM69Time,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM69Time"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM70Position),
		(ASN_TAG_CLASS_CONTEXT | (70 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM70Position,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM70Position"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM71Time),
		(ASN_TAG_CLASS_CONTEXT | (71 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM71Time,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM71Time"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM72NULL),
		(ASN_TAG_CLASS_CONTEXT | (72 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM72NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM72NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM73Predepartureclearance),
		(ASN_TAG_CLASS_CONTEXT | (73 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM73Predepartureclearance,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM73Predepartureclearance"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM74Position),
		(ASN_TAG_CLASS_CONTEXT | (74 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM74Position,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM74Position"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM75Position),
		(ASN_TAG_CLASS_CONTEXT | (75 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM75Position,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM75Position"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM76TimePosition),
		(ASN_TAG_CLASS_CONTEXT | (76 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM76TimePosition,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM76TimePosition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM77PositionPosition),
		(ASN_TAG_CLASS_CONTEXT | (77 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM77PositionPosition,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM77PositionPosition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM78AltitudePosition),
		(ASN_TAG_CLASS_CONTEXT | (78 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM78AltitudePosition,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM78AltitudePosition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM79PositionRouteclearance),
		(ASN_TAG_CLASS_CONTEXT | (79 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM79PositionRouteclearance,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM79PositionRouteclearance"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM80Routeclearance),
		(ASN_TAG_CLASS_CONTEXT | (80 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM80Routeclearance,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM80Routeclearance"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM81Procedurename),
		(ASN_TAG_CLASS_CONTEXT | (81 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM81Procedurename,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM81Procedurename"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM82DistanceoffsetDirection),
		(ASN_TAG_CLASS_CONTEXT | (82 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM82DistanceoffsetDirection,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM82DistanceoffsetDirection"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM83PositionRouteclearance),
		(ASN_TAG_CLASS_CONTEXT | (83 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM83PositionRouteclearance,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM83PositionRouteclearance"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM84PositionProcedurename),
		(ASN_TAG_CLASS_CONTEXT | (84 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM84PositionProcedurename,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM84PositionProcedurename"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM85Routeclearance),
		(ASN_TAG_CLASS_CONTEXT | (85 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM85Routeclearance,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM85Routeclearance"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM86PositionRouteclearance),
		(ASN_TAG_CLASS_CONTEXT | (86 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM86PositionRouteclearance,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM86PositionRouteclearance"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM87Position),
		(ASN_TAG_CLASS_CONTEXT | (87 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM87Position,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM87Position"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM88PositionPosition),
		(ASN_TAG_CLASS_CONTEXT | (88 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM88PositionPosition,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM88PositionPosition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM89TimePosition),
		(ASN_TAG_CLASS_CONTEXT | (89 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM89TimePosition,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM89TimePosition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM90AltitudePosition),
		(ASN_TAG_CLASS_CONTEXT | (90 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM90AltitudePosition,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM90AltitudePosition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM91Holdclearance),
		(ASN_TAG_CLASS_CONTEXT | (91 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM91Holdclearance,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM91Holdclearance"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM92PositionAltitude),
		(ASN_TAG_CLASS_CONTEXT | (92 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM92PositionAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM92PositionAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM93Time),
		(ASN_TAG_CLASS_CONTEXT | (93 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM93Time,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM93Time"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM94DirectionDegrees),
		(ASN_TAG_CLASS_CONTEXT | (94 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM94DirectionDegrees,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM94DirectionDegrees"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM95DirectionDegrees),
		(ASN_TAG_CLASS_CONTEXT | (95 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM95DirectionDegrees,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM95DirectionDegrees"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM96NULL),
		(ASN_TAG_CLASS_CONTEXT | (96 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM96NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM96NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM97PositionDegrees),
		(ASN_TAG_CLASS_CONTEXT | (97 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM97PositionDegrees,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM97PositionDegrees"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM98DirectionDegrees),
		(ASN_TAG_CLASS_CONTEXT | (98 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM98DirectionDegrees,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM98DirectionDegrees"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM99Procedurename),
		(ASN_TAG_CLASS_CONTEXT | (99 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM99Procedurename,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM99Procedurename"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM100TimeSpeed),
		(ASN_TAG_CLASS_CONTEXT | (100 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM100TimeSpeed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM100TimeSpeed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM101PositionSpeed),
		(ASN_TAG_CLASS_CONTEXT | (101 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM101PositionSpeed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM101PositionSpeed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM102AltitudeSpeed),
		(ASN_TAG_CLASS_CONTEXT | (102 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM102AltitudeSpeed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM102AltitudeSpeed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM103TimeSpeedSpeed),
		(ASN_TAG_CLASS_CONTEXT | (103 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM103TimeSpeedSpeed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM103TimeSpeedSpeed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM104PositionSpeedSpeed),
		(ASN_TAG_CLASS_CONTEXT | (104 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM104PositionSpeedSpeed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM104PositionSpeedSpeed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM105AltitudeSpeedSpeed),
		(ASN_TAG_CLASS_CONTEXT | (105 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM105AltitudeSpeedSpeed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM105AltitudeSpeedSpeed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM106Speed),
		(ASN_TAG_CLASS_CONTEXT | (106 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM106Speed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM106Speed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM107NULL),
		(ASN_TAG_CLASS_CONTEXT | (107 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM107NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM107NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM108Speed),
		(ASN_TAG_CLASS_CONTEXT | (108 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM108Speed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM108Speed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM109Speed),
		(ASN_TAG_CLASS_CONTEXT | (109 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM109Speed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM109Speed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM110SpeedSpeed),
		(ASN_TAG_CLASS_CONTEXT | (110 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM110SpeedSpeed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM110SpeedSpeed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM111Speed),
		(ASN_TAG_CLASS_CONTEXT | (111 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM111Speed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM111Speed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM112Speed),
		(ASN_TAG_CLASS_CONTEXT | (112 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM112Speed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM112Speed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM113Speed),
		(ASN_TAG_CLASS_CONTEXT | (113 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM113Speed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM113Speed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM114Speed),
		(ASN_TAG_CLASS_CONTEXT | (114 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM114Speed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM114Speed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM115Speed),
		(ASN_TAG_CLASS_CONTEXT | (115 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM115Speed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM115Speed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM116NULL),
		(ASN_TAG_CLASS_CONTEXT | (116 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM116NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM116NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM117ICAOunitnameFrequency),
		(ASN_TAG_CLASS_CONTEXT | (117 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM117ICAOunitnameFrequency,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM117ICAOunitnameFrequency"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM118PositionICAOunitnameFrequency),
		(ASN_TAG_CLASS_CONTEXT | (118 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM118PositionICAOunitnameFrequency,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM118PositionICAOunitnameFrequency"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM119TimeICAOunitnameFrequency),
		(ASN_TAG_CLASS_CONTEXT | (119 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM119TimeICAOunitnameFrequency,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM119TimeICAOunitnameFrequency"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM120ICAOunitnameFrequency),
		(ASN_TAG_CLASS_CONTEXT | (120 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM120ICAOunitnameFrequency,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM120ICAOunitnameFrequency"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM121PositionICAOunitnameFrequency),
		(ASN_TAG_CLASS_CONTEXT | (121 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM121PositionICAOunitnameFrequency,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM121PositionICAOunitnameFrequency"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM122TimeICAOunitnameFrequency),
		(ASN_TAG_CLASS_CONTEXT | (122 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM122TimeICAOunitnameFrequency,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM122TimeICAOunitnameFrequency"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM123Beaconcode),
		(ASN_TAG_CLASS_CONTEXT | (123 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM123Beaconcode,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM123Beaconcode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM124NULL),
		(ASN_TAG_CLASS_CONTEXT | (124 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM124NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM124NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM125NULL),
		(ASN_TAG_CLASS_CONTEXT | (125 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM125NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM125NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM126NULL),
		(ASN_TAG_CLASS_CONTEXT | (126 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM126NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM126NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM127NULL),
		(ASN_TAG_CLASS_CONTEXT | (127 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM127NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM127NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM128Altitude),
		(ASN_TAG_CLASS_CONTEXT | (128 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM128Altitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM128Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM129Altitude),
		(ASN_TAG_CLASS_CONTEXT | (129 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM129Altitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM129Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM130Position),
		(ASN_TAG_CLASS_CONTEXT | (130 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM130Position,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM130Position"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM131NULL),
		(ASN_TAG_CLASS_CONTEXT | (131 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM131NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM131NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM132NULL),
		(ASN_TAG_CLASS_CONTEXT | (132 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM132NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM132NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM133NULL),
		(ASN_TAG_CLASS_CONTEXT | (133 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM133NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM133NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM134NULL),
		(ASN_TAG_CLASS_CONTEXT | (134 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM134NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM134NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM135NULL),
		(ASN_TAG_CLASS_CONTEXT | (135 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM135NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM135NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM136NULL),
		(ASN_TAG_CLASS_CONTEXT | (136 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM136NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM136NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM137NULL),
		(ASN_TAG_CLASS_CONTEXT | (137 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM137NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM137NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM138NULL),
		(ASN_TAG_CLASS_CONTEXT | (138 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM138NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM138NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM139NULL),
		(ASN_TAG_CLASS_CONTEXT | (139 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM139NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM139NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM140NULL),
		(ASN_TAG_CLASS_CONTEXT | (140 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM140NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM140NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM141NULL),
		(ASN_TAG_CLASS_CONTEXT | (141 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM141NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM141NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM142NULL),
		(ASN_TAG_CLASS_CONTEXT | (142 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM142NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM142NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM143NULL),
		(ASN_TAG_CLASS_CONTEXT | (143 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM143NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM143NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM144NULL),
		(ASN_TAG_CLASS_CONTEXT | (144 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM144NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM144NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM145NULL),
		(ASN_TAG_CLASS_CONTEXT | (145 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM145NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM145NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM146NULL),
		(ASN_TAG_CLASS_CONTEXT | (146 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM146NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM146NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM147NULL),
		(ASN_TAG_CLASS_CONTEXT | (147 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM147NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM147NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM148Altitude),
		(ASN_TAG_CLASS_CONTEXT | (148 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM148Altitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM148Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM149AltitudePosition),
		(ASN_TAG_CLASS_CONTEXT | (149 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM149AltitudePosition,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM149AltitudePosition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM150AltitudeTime),
		(ASN_TAG_CLASS_CONTEXT | (150 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM150AltitudeTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM150AltitudeTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM151Speed),
		(ASN_TAG_CLASS_CONTEXT | (151 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM151Speed,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM151Speed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM152DistanceoffsetDirection),
		(ASN_TAG_CLASS_CONTEXT | (152 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM152DistanceoffsetDirection,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM152DistanceoffsetDirection"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM153Altimeter),
		(ASN_TAG_CLASS_CONTEXT | (153 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM153Altimeter,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM153Altimeter"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM154NULL),
		(ASN_TAG_CLASS_CONTEXT | (154 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM154NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM154NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM155Position),
		(ASN_TAG_CLASS_CONTEXT | (155 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM155Position,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM155Position"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM156NULL),
		(ASN_TAG_CLASS_CONTEXT | (156 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM156NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM156NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM157Frequency),
		(ASN_TAG_CLASS_CONTEXT | (157 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM157Frequency,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM157Frequency"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM158Atiscode),
		(ASN_TAG_CLASS_CONTEXT | (158 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM158Atiscode,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM158Atiscode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM159Errorinformation),
		(ASN_TAG_CLASS_CONTEXT | (159 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM159Errorinformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM159Errorinformation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM160ICAOfacilitydesignation),
		(ASN_TAG_CLASS_CONTEXT | (160 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM160ICAOfacilitydesignation,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM160ICAOfacilitydesignation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM161NULL),
		(ASN_TAG_CLASS_CONTEXT | (161 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM161NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM161NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM162NULL),
		(ASN_TAG_CLASS_CONTEXT | (162 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM162NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM162NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM163ICAOfacilitydesignationTp4table),
		(ASN_TAG_CLASS_CONTEXT | (163 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM163ICAOfacilitydesignationTp4table,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM163ICAOfacilitydesignationTp4table"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM164NULL),
		(ASN_TAG_CLASS_CONTEXT | (164 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM164NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM164NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM165NULL),
		(ASN_TAG_CLASS_CONTEXT | (165 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM165NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM165NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM166NULL),
		(ASN_TAG_CLASS_CONTEXT | (166 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM166NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM166NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM167NULL),
		(ASN_TAG_CLASS_CONTEXT | (167 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM167NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM167NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM168NULL),
		(ASN_TAG_CLASS_CONTEXT | (168 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM168NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM168NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM169Freetext),
		(ASN_TAG_CLASS_CONTEXT | (169 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM169Freetext,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM169Freetext"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM170Freetext),
		(ASN_TAG_CLASS_CONTEXT | (170 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM170Freetext,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM170Freetext"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM171Verticalrate),
		(ASN_TAG_CLASS_CONTEXT | (171 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM171Verticalrate,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM171Verticalrate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM172Verticalrate),
		(ASN_TAG_CLASS_CONTEXT | (172 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM172Verticalrate,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM172Verticalrate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM173Verticalrate),
		(ASN_TAG_CLASS_CONTEXT | (173 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM173Verticalrate,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM173Verticalrate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM174Verticalrate),
		(ASN_TAG_CLASS_CONTEXT | (174 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM174Verticalrate,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM174Verticalrate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM175Altitude),
		(ASN_TAG_CLASS_CONTEXT | (175 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UM175Altitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM175Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM176NULL),
		(ASN_TAG_CLASS_CONTEXT | (176 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM176NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM176NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM177NULL),
		(ASN_TAG_CLASS_CONTEXT | (177 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM177NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM177NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM178NULL),
		(ASN_TAG_CLASS_CONTEXT | (178 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM178NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM178NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM179NULL),
		(ASN_TAG_CLASS_CONTEXT | (179 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM179NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM179NULL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM180AltitudeAltitude),
		(ASN_TAG_CLASS_CONTEXT | (180 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM180AltitudeAltitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM180AltitudeAltitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM181TofromPosition),
		(ASN_TAG_CLASS_CONTEXT | (181 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM181TofromPosition,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM181TofromPosition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ATCuplinkmsgelementid, choice.uM182NULL),
		(ASN_TAG_CLASS_CONTEXT | (182 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UM182NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uM182NULL"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ATCuplinkmsgelementid_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* uM0NULL */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* uM1NULL */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* uM2NULL */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* uM3NULL */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* uM4NULL */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* uM5NULL */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* uM6Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* uM7Time */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* uM8Position */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* uM9Time */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* uM10Position */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* uM11Time */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* uM12Position */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* uM13TimeAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* uM14PositionAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 }, /* uM15TimeAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 16, 0, 0 }, /* uM16PositionAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 17, 0, 0 }, /* uM17TimeAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 18, 0, 0 }, /* uM18PositionAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 19, 0, 0 }, /* uM19Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 20, 0, 0 }, /* uM20Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 21, 0, 0 }, /* uM21TimeAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 22, 0, 0 }, /* uM22PositionAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 23, 0, 0 }, /* uM23Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 24, 0, 0 }, /* uM24TimeAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 25, 0, 0 }, /* uM25PositionAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (26 << 2)), 26, 0, 0 }, /* uM26AltitudeTime */
    { (ASN_TAG_CLASS_CONTEXT | (27 << 2)), 27, 0, 0 }, /* uM27AltitudePosition */
    { (ASN_TAG_CLASS_CONTEXT | (28 << 2)), 28, 0, 0 }, /* uM28AltitudeTime */
    { (ASN_TAG_CLASS_CONTEXT | (29 << 2)), 29, 0, 0 }, /* uM29AltitudePosition */
    { (ASN_TAG_CLASS_CONTEXT | (30 << 2)), 30, 0, 0 }, /* uM30AltitudeAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (31 << 2)), 31, 0, 0 }, /* uM31AltitudeAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (32 << 2)), 32, 0, 0 }, /* uM32AltitudeAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (33 << 2)), 33, 0, 0 }, /* uM33Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (34 << 2)), 34, 0, 0 }, /* uM34Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (35 << 2)), 35, 0, 0 }, /* uM35Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (36 << 2)), 36, 0, 0 }, /* uM36Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (37 << 2)), 37, 0, 0 }, /* uM37Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (38 << 2)), 38, 0, 0 }, /* uM38Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (39 << 2)), 39, 0, 0 }, /* uM39Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (40 << 2)), 40, 0, 0 }, /* uM40Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (41 << 2)), 41, 0, 0 }, /* uM41Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (42 << 2)), 42, 0, 0 }, /* uM42PositionAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (43 << 2)), 43, 0, 0 }, /* uM43PositionAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (44 << 2)), 44, 0, 0 }, /* uM44PositionAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (45 << 2)), 45, 0, 0 }, /* uM45PositionAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (46 << 2)), 46, 0, 0 }, /* uM46PositionAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (47 << 2)), 47, 0, 0 }, /* uM47PositionAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (48 << 2)), 48, 0, 0 }, /* uM48PositionAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (49 << 2)), 49, 0, 0 }, /* uM49PositionAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (50 << 2)), 50, 0, 0 }, /* uM50PositionAltitudeAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (51 << 2)), 51, 0, 0 }, /* uM51PositionTime */
    { (ASN_TAG_CLASS_CONTEXT | (52 << 2)), 52, 0, 0 }, /* uM52PositionTime */
    { (ASN_TAG_CLASS_CONTEXT | (53 << 2)), 53, 0, 0 }, /* uM53PositionTime */
    { (ASN_TAG_CLASS_CONTEXT | (54 << 2)), 54, 0, 0 }, /* uM54PositionTimeTime */
    { (ASN_TAG_CLASS_CONTEXT | (55 << 2)), 55, 0, 0 }, /* uM55PositionSpeed */
    { (ASN_TAG_CLASS_CONTEXT | (56 << 2)), 56, 0, 0 }, /* uM56PositionSpeed */
    { (ASN_TAG_CLASS_CONTEXT | (57 << 2)), 57, 0, 0 }, /* uM57PositionSpeed */
    { (ASN_TAG_CLASS_CONTEXT | (58 << 2)), 58, 0, 0 }, /* uM58PositionTimeAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (59 << 2)), 59, 0, 0 }, /* uM59PositionTimeAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (60 << 2)), 60, 0, 0 }, /* uM60PositionTimeAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (61 << 2)), 61, 0, 0 }, /* uM61PositionAltitudeSpeed */
    { (ASN_TAG_CLASS_CONTEXT | (62 << 2)), 62, 0, 0 }, /* uM62TimePositionAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (63 << 2)), 63, 0, 0 }, /* uM63TimePositionAltitudeSpeed */
    { (ASN_TAG_CLASS_CONTEXT | (64 << 2)), 64, 0, 0 }, /* uM64DistanceoffsetDirection */
    { (ASN_TAG_CLASS_CONTEXT | (65 << 2)), 65, 0, 0 }, /* uM65PositionDistanceoffsetDirection */
    { (ASN_TAG_CLASS_CONTEXT | (66 << 2)), 66, 0, 0 }, /* uM66TimeDistanceoffsetDirection */
    { (ASN_TAG_CLASS_CONTEXT | (67 << 2)), 67, 0, 0 }, /* uM67NULL */
    { (ASN_TAG_CLASS_CONTEXT | (68 << 2)), 68, 0, 0 }, /* uM68Position */
    { (ASN_TAG_CLASS_CONTEXT | (69 << 2)), 69, 0, 0 }, /* uM69Time */
    { (ASN_TAG_CLASS_CONTEXT | (70 << 2)), 70, 0, 0 }, /* uM70Position */
    { (ASN_TAG_CLASS_CONTEXT | (71 << 2)), 71, 0, 0 }, /* uM71Time */
    { (ASN_TAG_CLASS_CONTEXT | (72 << 2)), 72, 0, 0 }, /* uM72NULL */
    { (ASN_TAG_CLASS_CONTEXT | (73 << 2)), 73, 0, 0 }, /* uM73Predepartureclearance */
    { (ASN_TAG_CLASS_CONTEXT | (74 << 2)), 74, 0, 0 }, /* uM74Position */
    { (ASN_TAG_CLASS_CONTEXT | (75 << 2)), 75, 0, 0 }, /* uM75Position */
    { (ASN_TAG_CLASS_CONTEXT | (76 << 2)), 76, 0, 0 }, /* uM76TimePosition */
    { (ASN_TAG_CLASS_CONTEXT | (77 << 2)), 77, 0, 0 }, /* uM77PositionPosition */
    { (ASN_TAG_CLASS_CONTEXT | (78 << 2)), 78, 0, 0 }, /* uM78AltitudePosition */
    { (ASN_TAG_CLASS_CONTEXT | (79 << 2)), 79, 0, 0 }, /* uM79PositionRouteclearance */
    { (ASN_TAG_CLASS_CONTEXT | (80 << 2)), 80, 0, 0 }, /* uM80Routeclearance */
    { (ASN_TAG_CLASS_CONTEXT | (81 << 2)), 81, 0, 0 }, /* uM81Procedurename */
    { (ASN_TAG_CLASS_CONTEXT | (82 << 2)), 82, 0, 0 }, /* uM82DistanceoffsetDirection */
    { (ASN_TAG_CLASS_CONTEXT | (83 << 2)), 83, 0, 0 }, /* uM83PositionRouteclearance */
    { (ASN_TAG_CLASS_CONTEXT | (84 << 2)), 84, 0, 0 }, /* uM84PositionProcedurename */
    { (ASN_TAG_CLASS_CONTEXT | (85 << 2)), 85, 0, 0 }, /* uM85Routeclearance */
    { (ASN_TAG_CLASS_CONTEXT | (86 << 2)), 86, 0, 0 }, /* uM86PositionRouteclearance */
    { (ASN_TAG_CLASS_CONTEXT | (87 << 2)), 87, 0, 0 }, /* uM87Position */
    { (ASN_TAG_CLASS_CONTEXT | (88 << 2)), 88, 0, 0 }, /* uM88PositionPosition */
    { (ASN_TAG_CLASS_CONTEXT | (89 << 2)), 89, 0, 0 }, /* uM89TimePosition */
    { (ASN_TAG_CLASS_CONTEXT | (90 << 2)), 90, 0, 0 }, /* uM90AltitudePosition */
    { (ASN_TAG_CLASS_CONTEXT | (91 << 2)), 91, 0, 0 }, /* uM91Holdclearance */
    { (ASN_TAG_CLASS_CONTEXT | (92 << 2)), 92, 0, 0 }, /* uM92PositionAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (93 << 2)), 93, 0, 0 }, /* uM93Time */
    { (ASN_TAG_CLASS_CONTEXT | (94 << 2)), 94, 0, 0 }, /* uM94DirectionDegrees */
    { (ASN_TAG_CLASS_CONTEXT | (95 << 2)), 95, 0, 0 }, /* uM95DirectionDegrees */
    { (ASN_TAG_CLASS_CONTEXT | (96 << 2)), 96, 0, 0 }, /* uM96NULL */
    { (ASN_TAG_CLASS_CONTEXT | (97 << 2)), 97, 0, 0 }, /* uM97PositionDegrees */
    { (ASN_TAG_CLASS_CONTEXT | (98 << 2)), 98, 0, 0 }, /* uM98DirectionDegrees */
    { (ASN_TAG_CLASS_CONTEXT | (99 << 2)), 99, 0, 0 }, /* uM99Procedurename */
    { (ASN_TAG_CLASS_CONTEXT | (100 << 2)), 100, 0, 0 }, /* uM100TimeSpeed */
    { (ASN_TAG_CLASS_CONTEXT | (101 << 2)), 101, 0, 0 }, /* uM101PositionSpeed */
    { (ASN_TAG_CLASS_CONTEXT | (102 << 2)), 102, 0, 0 }, /* uM102AltitudeSpeed */
    { (ASN_TAG_CLASS_CONTEXT | (103 << 2)), 103, 0, 0 }, /* uM103TimeSpeedSpeed */
    { (ASN_TAG_CLASS_CONTEXT | (104 << 2)), 104, 0, 0 }, /* uM104PositionSpeedSpeed */
    { (ASN_TAG_CLASS_CONTEXT | (105 << 2)), 105, 0, 0 }, /* uM105AltitudeSpeedSpeed */
    { (ASN_TAG_CLASS_CONTEXT | (106 << 2)), 106, 0, 0 }, /* uM106Speed */
    { (ASN_TAG_CLASS_CONTEXT | (107 << 2)), 107, 0, 0 }, /* uM107NULL */
    { (ASN_TAG_CLASS_CONTEXT | (108 << 2)), 108, 0, 0 }, /* uM108Speed */
    { (ASN_TAG_CLASS_CONTEXT | (109 << 2)), 109, 0, 0 }, /* uM109Speed */
    { (ASN_TAG_CLASS_CONTEXT | (110 << 2)), 110, 0, 0 }, /* uM110SpeedSpeed */
    { (ASN_TAG_CLASS_CONTEXT | (111 << 2)), 111, 0, 0 }, /* uM111Speed */
    { (ASN_TAG_CLASS_CONTEXT | (112 << 2)), 112, 0, 0 }, /* uM112Speed */
    { (ASN_TAG_CLASS_CONTEXT | (113 << 2)), 113, 0, 0 }, /* uM113Speed */
    { (ASN_TAG_CLASS_CONTEXT | (114 << 2)), 114, 0, 0 }, /* uM114Speed */
    { (ASN_TAG_CLASS_CONTEXT | (115 << 2)), 115, 0, 0 }, /* uM115Speed */
    { (ASN_TAG_CLASS_CONTEXT | (116 << 2)), 116, 0, 0 }, /* uM116NULL */
    { (ASN_TAG_CLASS_CONTEXT | (117 << 2)), 117, 0, 0 }, /* uM117ICAOunitnameFrequency */
    { (ASN_TAG_CLASS_CONTEXT | (118 << 2)), 118, 0, 0 }, /* uM118PositionICAOunitnameFrequency */
    { (ASN_TAG_CLASS_CONTEXT | (119 << 2)), 119, 0, 0 }, /* uM119TimeICAOunitnameFrequency */
    { (ASN_TAG_CLASS_CONTEXT | (120 << 2)), 120, 0, 0 }, /* uM120ICAOunitnameFrequency */
    { (ASN_TAG_CLASS_CONTEXT | (121 << 2)), 121, 0, 0 }, /* uM121PositionICAOunitnameFrequency */
    { (ASN_TAG_CLASS_CONTEXT | (122 << 2)), 122, 0, 0 }, /* uM122TimeICAOunitnameFrequency */
    { (ASN_TAG_CLASS_CONTEXT | (123 << 2)), 123, 0, 0 }, /* uM123Beaconcode */
    { (ASN_TAG_CLASS_CONTEXT | (124 << 2)), 124, 0, 0 }, /* uM124NULL */
    { (ASN_TAG_CLASS_CONTEXT | (125 << 2)), 125, 0, 0 }, /* uM125NULL */
    { (ASN_TAG_CLASS_CONTEXT | (126 << 2)), 126, 0, 0 }, /* uM126NULL */
    { (ASN_TAG_CLASS_CONTEXT | (127 << 2)), 127, 0, 0 }, /* uM127NULL */
    { (ASN_TAG_CLASS_CONTEXT | (128 << 2)), 128, 0, 0 }, /* uM128Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (129 << 2)), 129, 0, 0 }, /* uM129Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (130 << 2)), 130, 0, 0 }, /* uM130Position */
    { (ASN_TAG_CLASS_CONTEXT | (131 << 2)), 131, 0, 0 }, /* uM131NULL */
    { (ASN_TAG_CLASS_CONTEXT | (132 << 2)), 132, 0, 0 }, /* uM132NULL */
    { (ASN_TAG_CLASS_CONTEXT | (133 << 2)), 133, 0, 0 }, /* uM133NULL */
    { (ASN_TAG_CLASS_CONTEXT | (134 << 2)), 134, 0, 0 }, /* uM134NULL */
    { (ASN_TAG_CLASS_CONTEXT | (135 << 2)), 135, 0, 0 }, /* uM135NULL */
    { (ASN_TAG_CLASS_CONTEXT | (136 << 2)), 136, 0, 0 }, /* uM136NULL */
    { (ASN_TAG_CLASS_CONTEXT | (137 << 2)), 137, 0, 0 }, /* uM137NULL */
    { (ASN_TAG_CLASS_CONTEXT | (138 << 2)), 138, 0, 0 }, /* uM138NULL */
    { (ASN_TAG_CLASS_CONTEXT | (139 << 2)), 139, 0, 0 }, /* uM139NULL */
    { (ASN_TAG_CLASS_CONTEXT | (140 << 2)), 140, 0, 0 }, /* uM140NULL */
    { (ASN_TAG_CLASS_CONTEXT | (141 << 2)), 141, 0, 0 }, /* uM141NULL */
    { (ASN_TAG_CLASS_CONTEXT | (142 << 2)), 142, 0, 0 }, /* uM142NULL */
    { (ASN_TAG_CLASS_CONTEXT | (143 << 2)), 143, 0, 0 }, /* uM143NULL */
    { (ASN_TAG_CLASS_CONTEXT | (144 << 2)), 144, 0, 0 }, /* uM144NULL */
    { (ASN_TAG_CLASS_CONTEXT | (145 << 2)), 145, 0, 0 }, /* uM145NULL */
    { (ASN_TAG_CLASS_CONTEXT | (146 << 2)), 146, 0, 0 }, /* uM146NULL */
    { (ASN_TAG_CLASS_CONTEXT | (147 << 2)), 147, 0, 0 }, /* uM147NULL */
    { (ASN_TAG_CLASS_CONTEXT | (148 << 2)), 148, 0, 0 }, /* uM148Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (149 << 2)), 149, 0, 0 }, /* uM149AltitudePosition */
    { (ASN_TAG_CLASS_CONTEXT | (150 << 2)), 150, 0, 0 }, /* uM150AltitudeTime */
    { (ASN_TAG_CLASS_CONTEXT | (151 << 2)), 151, 0, 0 }, /* uM151Speed */
    { (ASN_TAG_CLASS_CONTEXT | (152 << 2)), 152, 0, 0 }, /* uM152DistanceoffsetDirection */
    { (ASN_TAG_CLASS_CONTEXT | (153 << 2)), 153, 0, 0 }, /* uM153Altimeter */
    { (ASN_TAG_CLASS_CONTEXT | (154 << 2)), 154, 0, 0 }, /* uM154NULL */
    { (ASN_TAG_CLASS_CONTEXT | (155 << 2)), 155, 0, 0 }, /* uM155Position */
    { (ASN_TAG_CLASS_CONTEXT | (156 << 2)), 156, 0, 0 }, /* uM156NULL */
    { (ASN_TAG_CLASS_CONTEXT | (157 << 2)), 157, 0, 0 }, /* uM157Frequency */
    { (ASN_TAG_CLASS_CONTEXT | (158 << 2)), 158, 0, 0 }, /* uM158Atiscode */
    { (ASN_TAG_CLASS_CONTEXT | (159 << 2)), 159, 0, 0 }, /* uM159Errorinformation */
    { (ASN_TAG_CLASS_CONTEXT | (160 << 2)), 160, 0, 0 }, /* uM160ICAOfacilitydesignation */
    { (ASN_TAG_CLASS_CONTEXT | (161 << 2)), 161, 0, 0 }, /* uM161NULL */
    { (ASN_TAG_CLASS_CONTEXT | (162 << 2)), 162, 0, 0 }, /* uM162NULL */
    { (ASN_TAG_CLASS_CONTEXT | (163 << 2)), 163, 0, 0 }, /* uM163ICAOfacilitydesignationTp4table */
    { (ASN_TAG_CLASS_CONTEXT | (164 << 2)), 164, 0, 0 }, /* uM164NULL */
    { (ASN_TAG_CLASS_CONTEXT | (165 << 2)), 165, 0, 0 }, /* uM165NULL */
    { (ASN_TAG_CLASS_CONTEXT | (166 << 2)), 166, 0, 0 }, /* uM166NULL */
    { (ASN_TAG_CLASS_CONTEXT | (167 << 2)), 167, 0, 0 }, /* uM167NULL */
    { (ASN_TAG_CLASS_CONTEXT | (168 << 2)), 168, 0, 0 }, /* uM168NULL */
    { (ASN_TAG_CLASS_CONTEXT | (169 << 2)), 169, 0, 0 }, /* uM169Freetext */
    { (ASN_TAG_CLASS_CONTEXT | (170 << 2)), 170, 0, 0 }, /* uM170Freetext */
    { (ASN_TAG_CLASS_CONTEXT | (171 << 2)), 171, 0, 0 }, /* uM171Verticalrate */
    { (ASN_TAG_CLASS_CONTEXT | (172 << 2)), 172, 0, 0 }, /* uM172Verticalrate */
    { (ASN_TAG_CLASS_CONTEXT | (173 << 2)), 173, 0, 0 }, /* uM173Verticalrate */
    { (ASN_TAG_CLASS_CONTEXT | (174 << 2)), 174, 0, 0 }, /* uM174Verticalrate */
    { (ASN_TAG_CLASS_CONTEXT | (175 << 2)), 175, 0, 0 }, /* uM175Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (176 << 2)), 176, 0, 0 }, /* uM176NULL */
    { (ASN_TAG_CLASS_CONTEXT | (177 << 2)), 177, 0, 0 }, /* uM177NULL */
    { (ASN_TAG_CLASS_CONTEXT | (178 << 2)), 178, 0, 0 }, /* uM178NULL */
    { (ASN_TAG_CLASS_CONTEXT | (179 << 2)), 179, 0, 0 }, /* uM179NULL */
    { (ASN_TAG_CLASS_CONTEXT | (180 << 2)), 180, 0, 0 }, /* uM180AltitudeAltitude */
    { (ASN_TAG_CLASS_CONTEXT | (181 << 2)), 181, 0, 0 }, /* uM181TofromPosition */
    { (ASN_TAG_CLASS_CONTEXT | (182 << 2)), 182, 0, 0 } /* uM182NULL */
};
static asn_CHOICE_specifics_t asn_SPC_ATCuplinkmsgelementid_specs_1 = {
	sizeof(struct ATCuplinkmsgelementid),
	offsetof(struct ATCuplinkmsgelementid, _asn_ctx),
	offsetof(struct ATCuplinkmsgelementid, present),
	sizeof(((struct ATCuplinkmsgelementid *)0)->present),
	asn_MAP_ATCuplinkmsgelementid_tag2el_1,
	183,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ATCuplinkmsgelementid = {
	"ATCuplinkmsgelementid",
	"ATCuplinkmsgelementid",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_ATCuplinkmsgelementid_constr_1,
	asn_MBR_ATCuplinkmsgelementid_1,
	183,	/* Elements count */
	&asn_SPC_ATCuplinkmsgelementid_specs_1	/* Additional specs */
};

