/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_ATWalongtrackwaypoint_H_
#define	_ATWalongtrackwaypoint_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Position.h"
#include "ATWdistance.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Speed;
struct ATWaltitudesequence;

/* ATWalongtrackwaypoint */
typedef struct ATWalongtrackwaypoint {
	Position_t	 position;
	ATWdistance_t	 aTWdistance;
	struct Speed	*speed	/* OPTIONAL */;
	struct ATWaltitudesequence	*aTWaltitudesequence	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ATWalongtrackwaypoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ATWalongtrackwaypoint;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Speed.h"
#include "ATWaltitudesequence.h"

#endif	/* _ATWalongtrackwaypoint_H_ */
#include <asn_internal.h>
