/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Beaconcodeoctaldigit_H_
#define	_Beaconcodeoctaldigit_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Beaconcodeoctaldigit */
typedef long	 Beaconcodeoctaldigit_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Beaconcodeoctaldigit;
asn_struct_free_f Beaconcodeoctaldigit_free;
asn_struct_print_f Beaconcodeoctaldigit_print;
asn_constr_check_f Beaconcodeoctaldigit_constraint;
ber_type_decoder_f Beaconcodeoctaldigit_decode_ber;
der_type_encoder_f Beaconcodeoctaldigit_encode_der;
xer_type_decoder_f Beaconcodeoctaldigit_decode_xer;
xer_type_encoder_f Beaconcodeoctaldigit_encode_xer;
per_type_decoder_f Beaconcodeoctaldigit_decode_uper;
per_type_encoder_f Beaconcodeoctaldigit_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Beaconcodeoctaldigit_H_ */
#include <asn_internal.h>
