/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_COMNAVequipmentstatus_H_
#define	_COMNAVequipmentstatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum COMNAVequipmentstatus {
	COMNAVequipmentstatus_aloranA	= 0,
	COMNAVequipmentstatus_cloranC	= 1,
	COMNAVequipmentstatus_ddme	= 2,
	COMNAVequipmentstatus_edecca	= 3,
	COMNAVequipmentstatus_fadf	= 4,
	COMNAVequipmentstatus_ggnss	= 5,
	COMNAVequipmentstatus_hhfRTF	= 6,
	COMNAVequipmentstatus_iinertialNavigation	= 7,
	COMNAVequipmentstatus_lils	= 8,
	COMNAVequipmentstatus_momega	= 9,
	COMNAVequipmentstatus_ovor	= 10,
	COMNAVequipmentstatus_pdoppler	= 11,
	COMNAVequipmentstatus_rrnavRouteEquipment	= 12,
	COMNAVequipmentstatus_ttacan	= 13,
	COMNAVequipmentstatus_uuhfRTF	= 14,
	COMNAVequipmentstatus_vvhfRTF	= 15
} e_COMNAVequipmentstatus;

/* COMNAVequipmentstatus */
typedef long	 COMNAVequipmentstatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_COMNAVequipmentstatus;
asn_struct_free_f COMNAVequipmentstatus_free;
asn_struct_print_f COMNAVequipmentstatus_print;
asn_constr_check_f COMNAVequipmentstatus_constraint;
ber_type_decoder_f COMNAVequipmentstatus_decode_ber;
der_type_encoder_f COMNAVequipmentstatus_encode_der;
xer_type_decoder_f COMNAVequipmentstatus_decode_xer;
xer_type_encoder_f COMNAVequipmentstatus_encode_xer;
per_type_decoder_f COMNAVequipmentstatus_decode_uper;
per_type_encoder_f COMNAVequipmentstatus_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _COMNAVequipmentstatus_H_ */
#include <asn_internal.h>
