/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Degreestrue_H_
#define	_Degreestrue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Degreestrue */
typedef long	 Degreestrue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Degreestrue;
asn_struct_free_f Degreestrue_free;
asn_struct_print_f Degreestrue_print;
asn_constr_check_f Degreestrue_constraint;
ber_type_decoder_f Degreestrue_decode_ber;
der_type_encoder_f Degreestrue_encode_der;
xer_type_decoder_f Degreestrue_decode_xer;
xer_type_encoder_f Degreestrue_encode_xer;
per_type_decoder_f Degreestrue_decode_uper;
per_type_encoder_f Degreestrue_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Degreestrue_H_ */
#include <asn_internal.h>
