/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Distancekm_H_
#define	_Distancekm_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Distancekm */
typedef long	 Distancekm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Distancekm;
asn_struct_free_f Distancekm_free;
asn_struct_print_f Distancekm_print;
asn_constr_check_f Distancekm_constraint;
ber_type_decoder_f Distancekm_decode_ber;
der_type_encoder_f Distancekm_encode_der;
xer_type_decoder_f Distancekm_decode_xer;
xer_type_encoder_f Distancekm_encode_xer;
per_type_decoder_f Distancekm_decode_uper;
per_type_encoder_f Distancekm_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Distancekm_H_ */
#include <asn_internal.h>
