/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Distancenm_H_
#define	_Distancenm_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Distancenm */
typedef long	 Distancenm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Distancenm;
asn_struct_free_f Distancenm_free;
asn_struct_print_f Distancenm_print;
asn_constr_check_f Distancenm_constraint;
ber_type_decoder_f Distancenm_decode_ber;
der_type_encoder_f Distancenm_encode_der;
xer_type_decoder_f Distancenm_decode_xer;
xer_type_encoder_f Distancenm_encode_xer;
per_type_decoder_f Distancenm_decode_uper;
per_type_encoder_f Distancenm_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Distancenm_H_ */
#include <asn_internal.h>
