/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_DM16PositionDistanceoffsetDirection_H_
#define	_DM16PositionDistanceoffsetDirection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PositionDistanceoffsetDirection.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DM16PositionDistanceoffsetDirection */
typedef PositionDistanceoffsetDirection_t	 DM16PositionDistanceoffsetDirection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DM16PositionDistanceoffsetDirection;
asn_struct_free_f DM16PositionDistanceoffsetDirection_free;
asn_struct_print_f DM16PositionDistanceoffsetDirection_print;
asn_constr_check_f DM16PositionDistanceoffsetDirection_constraint;
ber_type_decoder_f DM16PositionDistanceoffsetDirection_decode_ber;
der_type_encoder_f DM16PositionDistanceoffsetDirection_encode_der;
xer_type_decoder_f DM16PositionDistanceoffsetDirection_decode_xer;
xer_type_encoder_f DM16PositionDistanceoffsetDirection_encode_xer;
per_type_decoder_f DM16PositionDistanceoffsetDirection_decode_uper;
per_type_encoder_f DM16PositionDistanceoffsetDirection_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DM16PositionDistanceoffsetDirection_H_ */
#include <asn_internal.h>
