/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_DM17TimeDistanceoffsetDirection_H_
#define	_DM17TimeDistanceoffsetDirection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TimeDistanceoffsetDirection.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DM17TimeDistanceoffsetDirection */
typedef TimeDistanceoffsetDirection_t	 DM17TimeDistanceoffsetDirection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DM17TimeDistanceoffsetDirection;
asn_struct_free_f DM17TimeDistanceoffsetDirection_free;
asn_struct_print_f DM17TimeDistanceoffsetDirection_print;
asn_constr_check_f DM17TimeDistanceoffsetDirection_constraint;
ber_type_decoder_f DM17TimeDistanceoffsetDirection_decode_ber;
der_type_encoder_f DM17TimeDistanceoffsetDirection_encode_der;
xer_type_decoder_f DM17TimeDistanceoffsetDirection_decode_xer;
xer_type_encoder_f DM17TimeDistanceoffsetDirection_encode_xer;
per_type_decoder_f DM17TimeDistanceoffsetDirection_decode_uper;
per_type_encoder_f DM17TimeDistanceoffsetDirection_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DM17TimeDistanceoffsetDirection_H_ */
#include <asn_internal.h>
