/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_DM24Routeclearance_H_
#define	_DM24Routeclearance_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Routeclearance.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DM24Routeclearance */
typedef Routeclearance_t	 DM24Routeclearance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DM24Routeclearance;
asn_struct_free_f DM24Routeclearance_free;
asn_struct_print_f DM24Routeclearance_print;
asn_constr_check_f DM24Routeclearance_constraint;
ber_type_decoder_f DM24Routeclearance_decode_ber;
der_type_encoder_f DM24Routeclearance_encode_der;
xer_type_decoder_f DM24Routeclearance_decode_xer;
xer_type_encoder_f DM24Routeclearance_encode_xer;
per_type_decoder_f DM24Routeclearance_decode_uper;
per_type_encoder_f DM24Routeclearance_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DM24Routeclearance_H_ */
#include <asn_internal.h>
