/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_DM26PositionRouteclearance_H_
#define	_DM26PositionRouteclearance_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PositionRouteclearance.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DM26PositionRouteclearance */
typedef PositionRouteclearance_t	 DM26PositionRouteclearance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DM26PositionRouteclearance;
asn_struct_free_f DM26PositionRouteclearance_free;
asn_struct_print_f DM26PositionRouteclearance_print;
asn_constr_check_f DM26PositionRouteclearance_constraint;
ber_type_decoder_f DM26PositionRouteclearance_decode_ber;
der_type_encoder_f DM26PositionRouteclearance_encode_der;
xer_type_decoder_f DM26PositionRouteclearance_decode_xer;
xer_type_encoder_f DM26PositionRouteclearance_encode_xer;
per_type_decoder_f DM26PositionRouteclearance_decode_uper;
per_type_encoder_f DM26PositionRouteclearance_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DM26PositionRouteclearance_H_ */
#include <asn_internal.h>
