/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_DM36Degrees_H_
#define	_DM36Degrees_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Degrees.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DM36Degrees */
typedef Degrees_t	 DM36Degrees_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DM36Degrees;
asn_struct_free_f DM36Degrees_free;
asn_struct_print_f DM36Degrees_print;
asn_constr_check_f DM36Degrees_constraint;
ber_type_decoder_f DM36Degrees_decode_ber;
der_type_encoder_f DM36Degrees_encode_der;
xer_type_decoder_f DM36Degrees_decode_xer;
xer_type_encoder_f DM36Degrees_encode_xer;
per_type_decoder_f DM36Degrees_decode_uper;
per_type_encoder_f DM36Degrees_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DM36Degrees_H_ */
#include <asn_internal.h>
