/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_DM39Speed_H_
#define	_DM39Speed_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Speed.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DM39Speed */
typedef Speed_t	 DM39Speed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DM39Speed;
asn_struct_free_f DM39Speed_free;
asn_struct_print_f DM39Speed_print;
asn_constr_check_f DM39Speed_constraint;
ber_type_decoder_f DM39Speed_decode_ber;
der_type_encoder_f DM39Speed_encode_der;
xer_type_decoder_f DM39Speed_decode_xer;
xer_type_encoder_f DM39Speed_encode_xer;
per_type_decoder_f DM39Speed_decode_uper;
per_type_encoder_f DM39Speed_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DM39Speed_H_ */
#include <asn_internal.h>
