/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_DM45Position_H_
#define	_DM45Position_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Position.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DM45Position */
typedef Position_t	 DM45Position_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DM45Position;
asn_struct_free_f DM45Position_free;
asn_struct_print_f DM45Position_print;
asn_constr_check_f DM45Position_constraint;
ber_type_decoder_f DM45Position_decode_ber;
der_type_encoder_f DM45Position_encode_der;
xer_type_decoder_f DM45Position_decode_xer;
xer_type_encoder_f DM45Position_encode_xer;
per_type_decoder_f DM45Position_decode_uper;
per_type_encoder_f DM45Position_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DM45Position_H_ */
#include <asn_internal.h>
