/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_DM47Beaconcode_H_
#define	_DM47Beaconcode_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Beaconcode.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DM47Beaconcode */
typedef Beaconcode_t	 DM47Beaconcode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DM47Beaconcode;
asn_struct_free_f DM47Beaconcode_free;
asn_struct_print_f DM47Beaconcode_print;
asn_constr_check_f DM47Beaconcode_constraint;
ber_type_decoder_f DM47Beaconcode_decode_ber;
der_type_encoder_f DM47Beaconcode_encode_der;
xer_type_decoder_f DM47Beaconcode_decode_xer;
xer_type_encoder_f DM47Beaconcode_encode_xer;
per_type_decoder_f DM47Beaconcode_decode_uper;
per_type_encoder_f DM47Beaconcode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DM47Beaconcode_H_ */
#include <asn_internal.h>
