/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_DM48Positionreport_H_
#define	_DM48Positionreport_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Positionreport.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DM48Positionreport */
typedef Positionreport_t	 DM48Positionreport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DM48Positionreport;
asn_struct_free_f DM48Positionreport_free;
asn_struct_print_f DM48Positionreport_print;
asn_constr_check_f DM48Positionreport_constraint;
ber_type_decoder_f DM48Positionreport_decode_ber;
der_type_encoder_f DM48Positionreport_encode_der;
xer_type_decoder_f DM48Positionreport_decode_xer;
xer_type_encoder_f DM48Positionreport_encode_xer;
per_type_decoder_f DM48Positionreport_decode_uper;
per_type_encoder_f DM48Positionreport_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DM48Positionreport_H_ */
#include <asn_internal.h>
