/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_DM64ICAOfacilitydesignation_H_
#define	_DM64ICAOfacilitydesignation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ICAOfacilitydesignation.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DM64ICAOfacilitydesignation */
typedef ICAOfacilitydesignation_t	 DM64ICAOfacilitydesignation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DM64ICAOfacilitydesignation;
asn_struct_free_f DM64ICAOfacilitydesignation_free;
asn_struct_print_f DM64ICAOfacilitydesignation_print;
asn_constr_check_f DM64ICAOfacilitydesignation_constraint;
ber_type_decoder_f DM64ICAOfacilitydesignation_decode_ber;
der_type_encoder_f DM64ICAOfacilitydesignation_encode_der;
xer_type_decoder_f DM64ICAOfacilitydesignation_decode_xer;
xer_type_encoder_f DM64ICAOfacilitydesignation_encode_xer;
per_type_decoder_f DM64ICAOfacilitydesignation_decode_uper;
per_type_encoder_f DM64ICAOfacilitydesignation_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DM64ICAOfacilitydesignation_H_ */
#include <asn_internal.h>
