/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_DM72Altitude_H_
#define	_DM72Altitude_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Altitude.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DM72Altitude */
typedef Altitude_t	 DM72Altitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DM72Altitude;
asn_struct_free_f DM72Altitude_free;
asn_struct_print_f DM72Altitude_print;
asn_constr_check_f DM72Altitude_constraint;
ber_type_decoder_f DM72Altitude_decode_ber;
der_type_encoder_f DM72Altitude_encode_der;
xer_type_decoder_f DM72Altitude_decode_xer;
xer_type_encoder_f DM72Altitude_encode_xer;
per_type_decoder_f DM72Altitude_decode_uper;
per_type_encoder_f DM72Altitude_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DM72Altitude_H_ */
#include <asn_internal.h>
