/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_DM79Atiscode_H_
#define	_DM79Atiscode_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Atiscode.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DM79Atiscode */
typedef Atiscode_t	 DM79Atiscode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DM79Atiscode;
asn_struct_free_f DM79Atiscode_free;
asn_struct_print_f DM79Atiscode_print;
asn_constr_check_f DM79Atiscode_constraint;
ber_type_decoder_f DM79Atiscode_decode_ber;
der_type_encoder_f DM79Atiscode_encode_der;
xer_type_decoder_f DM79Atiscode_decode_xer;
xer_type_encoder_f DM79Atiscode_encode_xer;
per_type_decoder_f DM79Atiscode_decode_uper;
per_type_encoder_f DM79Atiscode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DM79Atiscode_H_ */
#include <asn_internal.h>
