/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_DM92NULL_H_
#define	_DM92NULL_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DM92NULL */
typedef NULL_t	 DM92NULL_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DM92NULL;
asn_struct_free_f DM92NULL_free;
asn_struct_print_f DM92NULL_print;
asn_constr_check_f DM92NULL_constraint;
ber_type_decoder_f DM92NULL_decode_ber;
der_type_encoder_f DM92NULL_encode_der;
xer_type_decoder_f DM92NULL_decode_xer;
xer_type_encoder_f DM92NULL_encode_xer;
per_type_decoder_f DM92NULL_decode_uper;
per_type_encoder_f DM92NULL_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DM92NULL_H_ */
#include <asn_internal.h>
