/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Frequencydeparture_H_
#define	_Frequencydeparture_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Frequencyvhf.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Frequencydeparture */
typedef Frequencyvhf_t	 Frequencydeparture_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Frequencydeparture;
asn_struct_free_f Frequencydeparture_free;
asn_struct_print_f Frequencydeparture_print;
asn_constr_check_f Frequencydeparture_constraint;
ber_type_decoder_f Frequencydeparture_decode_ber;
der_type_encoder_f Frequencydeparture_encode_der;
xer_type_decoder_f Frequencydeparture_decode_xer;
xer_type_encoder_f Frequencydeparture_encode_xer;
per_type_decoder_f Frequencydeparture_decode_uper;
per_type_encoder_f Frequencydeparture_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Frequencydeparture_H_ */
#include <asn_internal.h>
