/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Holdatwaypointspeedhigh_H_
#define	_Holdatwaypointspeedhigh_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Speed.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Holdatwaypointspeedhigh */
typedef Speed_t	 Holdatwaypointspeedhigh_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Holdatwaypointspeedhigh;
asn_struct_free_f Holdatwaypointspeedhigh_free;
asn_struct_print_f Holdatwaypointspeedhigh_print;
asn_constr_check_f Holdatwaypointspeedhigh_constraint;
ber_type_decoder_f Holdatwaypointspeedhigh_decode_ber;
der_type_encoder_f Holdatwaypointspeedhigh_encode_der;
xer_type_decoder_f Holdatwaypointspeedhigh_decode_xer;
xer_type_encoder_f Holdatwaypointspeedhigh_encode_xer;
per_type_decoder_f Holdatwaypointspeedhigh_decode_uper;
per_type_encoder_f Holdatwaypointspeedhigh_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Holdatwaypointspeedhigh_H_ */
#include <asn_internal.h>
