/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Holdatwaypoint_H_
#define	_Holdatwaypoint_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Position.h"
#include "Direction.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Speed;
struct ATWaltitude;
struct Degrees;
struct Time;
struct Legtype;

/* Holdatwaypoint */
typedef struct Holdatwaypoint {
	Position_t	 position;
	struct Speed	*holdatwaypointspeedlow	/* OPTIONAL */;
	struct ATWaltitude	*aTWaltitude	/* OPTIONAL */;
	struct Speed	*holdatwaypointspeedhigh	/* OPTIONAL */;
	Direction_t	*direction	/* OPTIONAL */;
	struct Degrees	*degrees	/* OPTIONAL */;
	struct Time	*eFCtime	/* OPTIONAL */;
	struct Legtype	*legtype	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Holdatwaypoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Holdatwaypoint;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Holdatwaypointspeedlow.h"
#include "ATWaltitude.h"
#include "Holdatwaypointspeedhigh.h"
#include "Degrees.h"
#include "EFCtime.h"
#include "Legtype.h"

#endif	/* _Holdatwaypoint_H_ */
#include <asn_internal.h>
