/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Holdclearance_H_
#define	_Holdclearance_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Position.h"
#include "Altitude.h"
#include "Degrees.h"
#include "Direction.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Legtype;

/* Holdclearance */
typedef struct Holdclearance {
	Position_t	 position;
	Altitude_t	 altitude;
	Degrees_t	 degrees;
	Direction_t	 direction;
	struct Legtype	*legtype	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Holdclearance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Holdclearance;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Legtype.h"

#endif	/* _Holdclearance_H_ */
#include <asn_internal.h>
