/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_ICAOfacilityidentification_H_
#define	_ICAOfacilityidentification_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ICAOfacilitydesignation.h"
#include "ICAOfacilityname.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ICAOfacilityidentification_PR {
	ICAOfacilityidentification_PR_NOTHING,	/* No components present */
	ICAOfacilityidentification_PR_iCAOfacilitydesignation,
	ICAOfacilityidentification_PR_iCAOfacilityname
} ICAOfacilityidentification_PR;

/* ICAOfacilityidentification */
typedef struct ICAOfacilityidentification {
	ICAOfacilityidentification_PR present;
	union ICAOfacilityidentification_u {
		ICAOfacilitydesignation_t	 iCAOfacilitydesignation;
		ICAOfacilityname_t	 iCAOfacilityname;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ICAOfacilityidentification_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ICAOfacilityidentification;

#ifdef __cplusplus
}
#endif

#endif	/* _ICAOfacilityidentification_H_ */
#include <asn_internal.h>
