/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_ICAOunitnameFrequency_H_
#define	_ICAOunitnameFrequency_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ICAOunitname.h"
#include "Frequency.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ICAOunitnameFrequency */
typedef struct ICAOunitnameFrequency {
	ICAOunitname_t	 iCAOunitname;
	Frequency_t	 frequency;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ICAOunitnameFrequency_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ICAOunitnameFrequency;

#ifdef __cplusplus
}
#endif

#endif	/* _ICAOunitnameFrequency_H_ */
#include <asn_internal.h>
