/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_ICAOfacilitydesignation_H_
#define	_ICAOfacilitydesignation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ICAOfacilitydesignation */
typedef IA5String_t	 ICAOfacilitydesignation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ICAOfacilitydesignation;
asn_struct_free_f ICAOfacilitydesignation_free;
asn_struct_print_f ICAOfacilitydesignation_print;
asn_constr_check_f ICAOfacilitydesignation_constraint;
ber_type_decoder_f ICAOfacilitydesignation_decode_ber;
der_type_encoder_f ICAOfacilitydesignation_encode_der;
xer_type_decoder_f ICAOfacilitydesignation_decode_xer;
xer_type_encoder_f ICAOfacilitydesignation_encode_xer;
per_type_decoder_f ICAOfacilitydesignation_decode_uper;
per_type_encoder_f ICAOfacilitydesignation_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ICAOfacilitydesignation_H_ */
#include <asn_internal.h>
