/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_ICAOfacilitydesignationTp4table_H_
#define	_ICAOfacilitydesignationTp4table_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ICAOfacilitydesignation.h"
#include "Tp4table.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ICAOfacilitydesignationTp4table */
typedef struct ICAOfacilitydesignationTp4table {
	ICAOfacilitydesignation_t	 iCAOfacilitydesignation;
	Tp4table_t	 tp4table;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ICAOfacilitydesignationTp4table_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ICAOfacilitydesignationTp4table;

#ifdef __cplusplus
}
#endif

#endif	/* _ICAOfacilitydesignationTp4table_H_ */
#include <asn_internal.h>
