/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#include "Interceptcoursefromselection.h"

static asn_per_constraints_t asn_PER_type_Interceptcoursefromselection_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_Interceptcoursefromselection_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Interceptcoursefromselection, choice.publishedidentifier),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Publishedidentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"publishedidentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Interceptcoursefromselection, choice.latitudeLongitude),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LatitudeLongitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"latitudeLongitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Interceptcoursefromselection, choice.placebearingplacebearing),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Placebearingplacebearing,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"placebearingplacebearing"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Interceptcoursefromselection, choice.placebearingdistance),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Placebearingdistance,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"placebearingdistance"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Interceptcoursefromselection_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* publishedidentifier */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* latitudeLongitude */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* placebearingplacebearing */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* placebearingdistance */
};
static asn_CHOICE_specifics_t asn_SPC_Interceptcoursefromselection_specs_1 = {
	sizeof(struct Interceptcoursefromselection),
	offsetof(struct Interceptcoursefromselection, _asn_ctx),
	offsetof(struct Interceptcoursefromselection, present),
	sizeof(((struct Interceptcoursefromselection *)0)->present),
	asn_MAP_Interceptcoursefromselection_tag2el_1,
	4,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Interceptcoursefromselection = {
	"Interceptcoursefromselection",
	"Interceptcoursefromselection",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_Interceptcoursefromselection_constr_1,
	asn_MBR_Interceptcoursefromselection_1,
	4,	/* Elements count */
	&asn_SPC_Interceptcoursefromselection_specs_1	/* Additional specs */
};

