/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Interceptcoursefromselection_H_
#define	_Interceptcoursefromselection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Publishedidentifier.h"
#include "LatitudeLongitude.h"
#include "Placebearingplacebearing.h"
#include "Placebearingdistance.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Interceptcoursefromselection_PR {
	Interceptcoursefromselection_PR_NOTHING,	/* No components present */
	Interceptcoursefromselection_PR_publishedidentifier,
	Interceptcoursefromselection_PR_latitudeLongitude,
	Interceptcoursefromselection_PR_placebearingplacebearing,
	Interceptcoursefromselection_PR_placebearingdistance
} Interceptcoursefromselection_PR;

/* Interceptcoursefromselection */
typedef struct Interceptcoursefromselection {
	Interceptcoursefromselection_PR present;
	union Interceptcoursefromselection_u {
		Publishedidentifier_t	 publishedidentifier;
		LatitudeLongitude_t	 latitudeLongitude;
		Placebearingplacebearing_t	 placebearingplacebearing;
		Placebearingdistance_t	 placebearingdistance;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Interceptcoursefromselection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Interceptcoursefromselection;

#ifdef __cplusplus
}
#endif

#endif	/* _Interceptcoursefromselection_H_ */
#include <asn_internal.h>
