/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Latitudedegrees_H_
#define	_Latitudedegrees_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Latitudedegrees */
typedef long	 Latitudedegrees_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Latitudedegrees;
asn_struct_free_f Latitudedegrees_free;
asn_struct_print_f Latitudedegrees_print;
asn_constr_check_f Latitudedegrees_constraint;
ber_type_decoder_f Latitudedegrees_decode_ber;
der_type_encoder_f Latitudedegrees_encode_der;
xer_type_decoder_f Latitudedegrees_decode_xer;
xer_type_encoder_f Latitudedegrees_encode_xer;
per_type_decoder_f Latitudedegrees_decode_uper;
per_type_encoder_f Latitudedegrees_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Latitudedegrees_H_ */
#include <asn_internal.h>
