/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Legdistanceenglish_H_
#define	_Legdistanceenglish_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Legdistanceenglish */
typedef long	 Legdistanceenglish_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Legdistanceenglish;
asn_struct_free_f Legdistanceenglish_free;
asn_struct_print_f Legdistanceenglish_print;
asn_constr_check_f Legdistanceenglish_constraint;
ber_type_decoder_f Legdistanceenglish_decode_ber;
der_type_encoder_f Legdistanceenglish_encode_der;
xer_type_decoder_f Legdistanceenglish_decode_xer;
xer_type_encoder_f Legdistanceenglish_encode_xer;
per_type_decoder_f Legdistanceenglish_decode_uper;
per_type_encoder_f Legdistanceenglish_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Legdistanceenglish_H_ */
#include <asn_internal.h>
