/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Legdistancemetric_H_
#define	_Legdistancemetric_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Legdistancemetric */
typedef long	 Legdistancemetric_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Legdistancemetric;
asn_struct_free_f Legdistancemetric_free;
asn_struct_print_f Legdistancemetric_print;
asn_constr_check_f Legdistancemetric_constraint;
ber_type_decoder_f Legdistancemetric_decode_ber;
der_type_encoder_f Legdistancemetric_encode_der;
xer_type_decoder_f Legdistancemetric_decode_xer;
xer_type_encoder_f Legdistancemetric_encode_xer;
per_type_decoder_f Legdistancemetric_decode_uper;
per_type_encoder_f Legdistancemetric_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Legdistancemetric_H_ */
#include <asn_internal.h>
