/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Legdistance_H_
#define	_Legdistance_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Legdistanceenglish.h"
#include "Legdistancemetric.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Legdistance_PR {
	Legdistance_PR_NOTHING,	/* No components present */
	Legdistance_PR_legdistanceenglish,
	Legdistance_PR_legdistancemetric
} Legdistance_PR;

/* Legdistance */
typedef struct Legdistance {
	Legdistance_PR present;
	union Legdistance_u {
		Legdistanceenglish_t	 legdistanceenglish;
		Legdistancemetric_t	 legdistancemetric;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Legdistance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Legdistance;

#ifdef __cplusplus
}
#endif

#endif	/* _Legdistance_H_ */
#include <asn_internal.h>
