/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Legtype_H_
#define	_Legtype_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Legdistance.h"
#include "Legtime.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Legtype_PR {
	Legtype_PR_NOTHING,	/* No components present */
	Legtype_PR_legdistance,
	Legtype_PR_legtime
} Legtype_PR;

/* Legtype */
typedef struct Legtype {
	Legtype_PR present;
	union Legtype_u {
		Legdistance_t	 legdistance;
		Legtime_t	 legtime;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Legtype_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Legtype;

#ifdef __cplusplus
}
#endif

#endif	/* _Legtype_H_ */
#include <asn_internal.h>
