/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Longitude_H_
#define	_Longitude_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Longitudedegrees.h"
#include "Minuteslatlon.h"
#include "Longitudedirection.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Longitude */
typedef struct Longitude {
	Longitudedegrees_t	 longitudedegrees;
	Minuteslatlon_t	*minuteslatlon	/* OPTIONAL */;
	Longitudedirection_t	 longitudedirection;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Longitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Longitude;

#ifdef __cplusplus
}
#endif

#endif	/* _Longitude_H_ */
#include <asn_internal.h>
