/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Longitudereportingpoints_H_
#define	_Longitudereportingpoints_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Longitudedirection.h"
#include "Longitudedegrees.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Longitudereportingpoints */
typedef struct Longitudereportingpoints {
	Longitudedirection_t	 longitudedirection;
	Longitudedegrees_t	 longitudedegrees;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Longitudereportingpoints_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Longitudereportingpoints;

#ifdef __cplusplus
}
#endif

#endif	/* _Longitudereportingpoints_H_ */
#include <asn_internal.h>
