/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#include "Longitudereportingpoints.h"

static asn_TYPE_member_t asn_MBR_Longitudereportingpoints_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Longitudereportingpoints, longitudedirection),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_Longitudedirection,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"longitudedirection"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Longitudereportingpoints, longitudedegrees),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Longitudedegrees,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"longitudedegrees"
		},
};
static const ber_tlv_tag_t asn_DEF_Longitudereportingpoints_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Longitudereportingpoints_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* longitudedegrees */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 0, 0, 0 } /* longitudedirection */
};
static asn_SEQUENCE_specifics_t asn_SPC_Longitudereportingpoints_specs_1 = {
	sizeof(struct Longitudereportingpoints),
	offsetof(struct Longitudereportingpoints, _asn_ctx),
	asn_MAP_Longitudereportingpoints_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Longitudereportingpoints = {
	"Longitudereportingpoints",
	"Longitudereportingpoints",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Longitudereportingpoints_tags_1,
	sizeof(asn_DEF_Longitudereportingpoints_tags_1)
		/sizeof(asn_DEF_Longitudereportingpoints_tags_1[0]), /* 1 */
	asn_DEF_Longitudereportingpoints_tags_1,	/* Same as above */
	sizeof(asn_DEF_Longitudereportingpoints_tags_1)
		/sizeof(asn_DEF_Longitudereportingpoints_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Longitudereportingpoints_1,
	2,	/* Elements count */
	&asn_SPC_Longitudereportingpoints_specs_1	/* Additional specs */
};

