/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_PositionTimeAltitude_H_
#define	_PositionTimeAltitude_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Position.h"
#include "Time.h"
#include "Altitude.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PositionTimeAltitude */
typedef struct PositionTimeAltitude {
	Position_t	 position;
	Time_t	 time;
	Altitude_t	 altitude;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PositionTimeAltitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PositionTimeAltitude;

#ifdef __cplusplus
}
#endif

#endif	/* _PositionTimeAltitude_H_ */
#include <asn_internal.h>
