/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_PositionSpeedSpeed_H_
#define	_PositionSpeedSpeed_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Position.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Speed;

/* PositionSpeedSpeed */
typedef struct PositionSpeedSpeed {
	Position_t	 position;
	struct PositionSpeedSpeed__speed_seqOf {
		A_SEQUENCE_OF(struct Speed) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} speed_seqOf;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PositionSpeedSpeed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PositionSpeedSpeed;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Speed.h"

#endif	/* _PositionSpeedSpeed_H_ */
#include <asn_internal.h>
