/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_PositionDistanceoffsetDirection_H_
#define	_PositionDistanceoffsetDirection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Position.h"
#include "Distanceoffset.h"
#include "Direction.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PositionDistanceoffsetDirection */
typedef struct PositionDistanceoffsetDirection {
	Position_t	 position;
	Distanceoffset_t	 distanceoffset;
	Direction_t	 direction;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PositionDistanceoffsetDirection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PositionDistanceoffsetDirection;

#ifdef __cplusplus
}
#endif

#endif	/* _PositionDistanceoffsetDirection_H_ */
#include <asn_internal.h>
