/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_PositionProcedurename_H_
#define	_PositionProcedurename_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Position.h"
#include "Procedurename.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PositionProcedurename */
typedef struct PositionProcedurename {
	Position_t	 position;
	Procedurename_t	 procedurename;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PositionProcedurename_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PositionProcedurename;

#ifdef __cplusplus
}
#endif

#endif	/* _PositionProcedurename_H_ */
#include <asn_internal.h>
