/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Predepartureclearance_H_
#define	_Predepartureclearance_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Aircraftflightidentification.h"
#include "Aircrafttype.h"
#include "Timedepartureedct.h"
#include "Routeclearance.h"
#include "Frequencydeparture.h"
#include "Beaconcode.h"
#include "PDCrevision.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Aircraftequipmentcode;
struct Altitude;

/* Predepartureclearance */
typedef struct Predepartureclearance {
	Aircraftflightidentification_t	 aircraftflightidentification;
	Aircrafttype_t	*aircrafttype	/* OPTIONAL */;
	struct Aircraftequipmentcode	*aircraftequipmentcode	/* OPTIONAL */;
	Timedepartureedct_t	 timedepartureedct;
	Routeclearance_t	 routeclearance;
	struct Altitude	*altituderestriction	/* OPTIONAL */;
	Frequencydeparture_t	 frequencydeparture;
	Beaconcode_t	 beaconcode;
	PDCrevision_t	 pDCrevision;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Predepartureclearance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Predepartureclearance;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Aircraftequipmentcode.h"
#include "Altituderestriction.h"

#endif	/* _Predepartureclearance_H_ */
#include <asn_internal.h>
