/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Proceduredeparture_H_
#define	_Proceduredeparture_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Procedurename.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Proceduredeparture */
typedef Procedurename_t	 Proceduredeparture_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Proceduredeparture;
asn_struct_free_f Proceduredeparture_free;
asn_struct_print_f Proceduredeparture_print;
asn_constr_check_f Proceduredeparture_constraint;
ber_type_decoder_f Proceduredeparture_decode_ber;
der_type_encoder_f Proceduredeparture_encode_der;
xer_type_decoder_f Proceduredeparture_decode_xer;
xer_type_encoder_f Proceduredeparture_encode_xer;
per_type_decoder_f Proceduredeparture_decode_uper;
per_type_encoder_f Proceduredeparture_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Proceduredeparture_H_ */
#include <asn_internal.h>
