/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Procedurearrival_H_
#define	_Procedurearrival_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Procedurename.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Procedurearrival */
typedef Procedurename_t	 Procedurearrival_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Procedurearrival;
asn_struct_free_f Procedurearrival_free;
asn_struct_print_f Procedurearrival_print;
asn_constr_check_f Procedurearrival_constraint;
ber_type_decoder_f Procedurearrival_decode_ber;
der_type_encoder_f Procedurearrival_encode_der;
xer_type_decoder_f Procedurearrival_decode_xer;
xer_type_encoder_f Procedurearrival_encode_xer;
per_type_decoder_f Procedurearrival_decode_uper;
per_type_encoder_f Procedurearrival_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Procedurearrival_H_ */
#include <asn_internal.h>
