/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Reportedwaypointtime_H_
#define	_Reportedwaypointtime_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Time.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Reportedwaypointtime */
typedef Time_t	 Reportedwaypointtime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Reportedwaypointtime;
asn_struct_free_f Reportedwaypointtime_free;
asn_struct_print_f Reportedwaypointtime_print;
asn_constr_check_f Reportedwaypointtime_constraint;
ber_type_decoder_f Reportedwaypointtime_decode_ber;
der_type_encoder_f Reportedwaypointtime_encode_der;
xer_type_decoder_f Reportedwaypointtime_decode_xer;
xer_type_encoder_f Reportedwaypointtime_encode_xer;
per_type_decoder_f Reportedwaypointtime_decode_uper;
per_type_encoder_f Reportedwaypointtime_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Reportedwaypointtime_H_ */
#include <asn_internal.h>
