/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Reportedwaypointposition_H_
#define	_Reportedwaypointposition_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Position.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Reportedwaypointposition */
typedef Position_t	 Reportedwaypointposition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Reportedwaypointposition;
asn_struct_free_f Reportedwaypointposition_free;
asn_struct_print_f Reportedwaypointposition_print;
asn_constr_check_f Reportedwaypointposition_constraint;
ber_type_decoder_f Reportedwaypointposition_decode_ber;
der_type_encoder_f Reportedwaypointposition_encode_der;
xer_type_decoder_f Reportedwaypointposition_decode_xer;
xer_type_encoder_f Reportedwaypointposition_encode_xer;
per_type_decoder_f Reportedwaypointposition_decode_uper;
per_type_encoder_f Reportedwaypointposition_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Reportedwaypointposition_H_ */
#include <asn_internal.h>
