/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Routeinformation_H_
#define	_Routeinformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Publishedidentifier.h"
#include "LatitudeLongitude.h"
#include "Placebearingplacebearing.h"
#include "Placebearingdistance.h"
#include "Airwayidentifier.h"
#include "Trackdetail.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Routeinformation_PR {
	Routeinformation_PR_NOTHING,	/* No components present */
	Routeinformation_PR_publishedidentifier,
	Routeinformation_PR_latitudeLongitude,
	Routeinformation_PR_placebearingplacebearing,
	Routeinformation_PR_placebearingdistance,
	Routeinformation_PR_airwayidentifier,
	Routeinformation_PR_trackdetail
} Routeinformation_PR;

/* Routeinformation */
typedef struct Routeinformation {
	Routeinformation_PR present;
	union Routeinformation_u {
		Publishedidentifier_t	 publishedidentifier;
		LatitudeLongitude_t	 latitudeLongitude;
		Placebearingplacebearing_t	 placebearingplacebearing;
		Placebearingdistance_t	 placebearingdistance;
		Airwayidentifier_t	 airwayidentifier;
		Trackdetail_t	 trackdetail;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Routeinformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Routeinformation;

#ifdef __cplusplus
}
#endif

#endif	/* _Routeinformation_H_ */
#include <asn_internal.h>
