/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Routeclearance_H_
#define	_Routeclearance_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Airportdeparture.h"
#include "Airportdestination.h"
#include "Airwayintercept.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Runway;
struct Procedurename;
struct Routeinformationadditional;
struct Routeinformation;

/* Routeclearance */
typedef struct Routeclearance {
	Airportdeparture_t	*airportdeparture	/* OPTIONAL */;
	Airportdestination_t	*airportdestination	/* OPTIONAL */;
	struct Runway	*runwaydeparture	/* OPTIONAL */;
	struct Procedurename	*proceduredeparture	/* OPTIONAL */;
	struct Runway	*runwayarrival	/* OPTIONAL */;
	struct Procedurename	*procedureapproach	/* OPTIONAL */;
	struct Procedurename	*procedurearrival	/* OPTIONAL */;
	Airwayintercept_t	*airwayintercept	/* OPTIONAL */;
	struct Routeclearance__routeinformation_seqOf {
		A_SEQUENCE_OF(struct Routeinformation) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *routeinformation_seqOf;
	struct Routeinformationadditional	*routeinformationadditional	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Routeclearance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Routeclearance;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Runwaydeparture.h"
#include "Proceduredeparture.h"
#include "Runwayarrival.h"
#include "Procedureapproach.h"
#include "Procedurearrival.h"
#include "Routeinformationadditional.h"
#include "Routeinformation.h"

#endif	/* _Routeclearance_H_ */
#include <asn_internal.h>
