/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#include "Routeinformationadditional.h"

static asn_TYPE_member_t asn_MBR_Routeinformationadditional_1[] = {
	{ ATF_POINTER, 6, offsetof(struct Routeinformationadditional, aTWalongtrackwaypointsequence),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ATWalongtrackwaypointsequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"aTWalongtrackwaypointsequence"
		},
	{ ATF_POINTER, 5, offsetof(struct Routeinformationadditional, reportingpoints),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Reportingpoints,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"reportingpoints"
		},
	{ ATF_POINTER, 4, offsetof(struct Routeinformationadditional, interceptcoursefromsequence),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Interceptcoursefromsequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"interceptcoursefromsequence"
		},
	{ ATF_POINTER, 3, offsetof(struct Routeinformationadditional, holdatwaypointsequence),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Holdatwaypointsequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"holdatwaypointsequence"
		},
	{ ATF_POINTER, 2, offsetof(struct Routeinformationadditional, waypointspeedaltitudesequence),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Waypointspeedaltitudesequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"waypointspeedaltitudesequence"
		},
	{ ATF_POINTER, 1, offsetof(struct Routeinformationadditional, rTArequiredtimearrivalsequenc),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RTArequiredtimearrivalsequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rTArequiredtimearrivalsequenc"
		},
};
static const int asn_MAP_Routeinformationadditional_oms_1[] = { 0, 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_Routeinformationadditional_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Routeinformationadditional_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* aTWalongtrackwaypointsequence */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* reportingpoints */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* interceptcoursefromsequence */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* holdatwaypointsequence */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* waypointspeedaltitudesequence */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* rTArequiredtimearrivalsequenc */
};
static asn_SEQUENCE_specifics_t asn_SPC_Routeinformationadditional_specs_1 = {
	sizeof(struct Routeinformationadditional),
	offsetof(struct Routeinformationadditional, _asn_ctx),
	asn_MAP_Routeinformationadditional_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_Routeinformationadditional_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Routeinformationadditional = {
	"Routeinformationadditional",
	"Routeinformationadditional",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Routeinformationadditional_tags_1,
	sizeof(asn_DEF_Routeinformationadditional_tags_1)
		/sizeof(asn_DEF_Routeinformationadditional_tags_1[0]), /* 1 */
	asn_DEF_Routeinformationadditional_tags_1,	/* Same as above */
	sizeof(asn_DEF_Routeinformationadditional_tags_1)
		/sizeof(asn_DEF_Routeinformationadditional_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Routeinformationadditional_1,
	6,	/* Elements count */
	&asn_SPC_Routeinformationadditional_specs_1	/* Additional specs */
};

