/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#include "Routeinformation.h"

static asn_per_constraints_t asn_PER_type_Routeinformation_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_Routeinformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Routeinformation, choice.publishedidentifier),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Publishedidentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"publishedidentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Routeinformation, choice.latitudeLongitude),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LatitudeLongitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"latitudeLongitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Routeinformation, choice.placebearingplacebearing),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Placebearingplacebearing,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"placebearingplacebearing"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Routeinformation, choice.placebearingdistance),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Placebearingdistance,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"placebearingdistance"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Routeinformation, choice.airwayidentifier),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Airwayidentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"airwayidentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Routeinformation, choice.trackdetail),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Trackdetail,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"trackdetail"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Routeinformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* publishedidentifier */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* latitudeLongitude */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* placebearingplacebearing */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* placebearingdistance */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* airwayidentifier */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* trackdetail */
};
static asn_CHOICE_specifics_t asn_SPC_Routeinformation_specs_1 = {
	sizeof(struct Routeinformation),
	offsetof(struct Routeinformation, _asn_ctx),
	offsetof(struct Routeinformation, present),
	sizeof(((struct Routeinformation *)0)->present),
	asn_MAP_Routeinformation_tag2el_1,
	6,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Routeinformation = {
	"Routeinformation",
	"Routeinformation",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_Routeinformation_constr_1,
	asn_MBR_Routeinformation_1,
	6,	/* Elements count */
	&asn_SPC_Routeinformation_specs_1	/* Additional specs */
};

