/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_RTArequiredtimearrival_H_
#define	_RTArequiredtimearrival_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Position.h"
#include "RTAtime.h"
#include "RTAtolerance.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RTArequiredtimearrival */
typedef struct RTArequiredtimearrival {
	Position_t	 position;
	RTAtime_t	 rTAtime;
	RTAtolerance_t	*rTAtolerance	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RTArequiredtimearrival_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RTArequiredtimearrival;

#ifdef __cplusplus
}
#endif

#endif	/* _RTArequiredtimearrival_H_ */
#include <asn_internal.h>
