/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_RTAtime_H_
#define	_RTAtime_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Time.h"
#include "Timetolerance.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RTAtime */
typedef struct RTAtime {
	Time_t	 time;
	Timetolerance_t	 timetolerance;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RTAtime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RTAtime;

#ifdef __cplusplus
}
#endif

#endif	/* _RTAtime_H_ */
#include <asn_internal.h>
