/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Speed_H_
#define	_Speed_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Speedindicated.h"
#include "Speedindicatedmetric.h"
#include "Speedtrue.h"
#include "Speedtruemetric.h"
#include "Speedground.h"
#include "Speedgroundmetric.h"
#include "Speedmach.h"
#include "Speedmachlarge.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Speed_PR {
	Speed_PR_NOTHING,	/* No components present */
	Speed_PR_speedindicated,
	Speed_PR_speedindicatedmetric,
	Speed_PR_speedtrue,
	Speed_PR_speedtruemetric,
	Speed_PR_speedground,
	Speed_PR_speedgroundmetric,
	Speed_PR_speedmach,
	Speed_PR_speedmachlarge
} Speed_PR;

/* Speed */
typedef struct Speed {
	Speed_PR present;
	union Speed_u {
		Speedindicated_t	 speedindicated;
		Speedindicatedmetric_t	 speedindicatedmetric;
		Speedtrue_t	 speedtrue;
		Speedtruemetric_t	 speedtruemetric;
		Speedground_t	 speedground;
		Speedgroundmetric_t	 speedgroundmetric;
		Speedmach_t	 speedmach;
		Speedmachlarge_t	 speedmachlarge;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Speed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Speed;

#ifdef __cplusplus
}
#endif

#endif	/* _Speed_H_ */
#include <asn_internal.h>
