/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Speedmachlarge_H_
#define	_Speedmachlarge_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Speedmachlarge */
typedef long	 Speedmachlarge_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Speedmachlarge;
asn_struct_free_f Speedmachlarge_free;
asn_struct_print_f Speedmachlarge_print;
asn_constr_check_f Speedmachlarge_constraint;
ber_type_decoder_f Speedmachlarge_decode_ber;
der_type_encoder_f Speedmachlarge_encode_der;
xer_type_decoder_f Speedmachlarge_decode_xer;
xer_type_encoder_f Speedmachlarge_encode_xer;
per_type_decoder_f Speedmachlarge_decode_uper;
per_type_encoder_f Speedmachlarge_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Speedmachlarge_H_ */
#include <asn_internal.h>
