/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Speedgroundmetric_H_
#define	_Speedgroundmetric_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Speedgroundmetric */
typedef long	 Speedgroundmetric_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Speedgroundmetric;
asn_struct_free_f Speedgroundmetric_free;
asn_struct_print_f Speedgroundmetric_print;
asn_constr_check_f Speedgroundmetric_constraint;
ber_type_decoder_f Speedgroundmetric_decode_ber;
der_type_encoder_f Speedgroundmetric_encode_der;
xer_type_decoder_f Speedgroundmetric_decode_xer;
xer_type_encoder_f Speedgroundmetric_encode_xer;
per_type_decoder_f Speedgroundmetric_decode_uper;
per_type_encoder_f Speedgroundmetric_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Speedgroundmetric_H_ */
#include <asn_internal.h>
