/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Speedmach_H_
#define	_Speedmach_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Speedmach */
typedef long	 Speedmach_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Speedmach;
asn_struct_free_f Speedmach_free;
asn_struct_print_f Speedmach_print;
asn_constr_check_f Speedmach_constraint;
ber_type_decoder_f Speedmach_decode_ber;
der_type_encoder_f Speedmach_encode_der;
xer_type_decoder_f Speedmach_decode_xer;
xer_type_encoder_f Speedmach_encode_xer;
per_type_decoder_f Speedmach_decode_uper;
per_type_encoder_f Speedmach_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Speedmach_H_ */
#include <asn_internal.h>
