/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Temperaturec_H_
#define	_Temperaturec_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Temperaturec */
typedef long	 Temperaturec_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Temperaturec;
asn_struct_free_f Temperaturec_free;
asn_struct_print_f Temperaturec_print;
asn_constr_check_f Temperaturec_constraint;
ber_type_decoder_f Temperaturec_decode_ber;
der_type_encoder_f Temperaturec_encode_der;
xer_type_decoder_f Temperaturec_decode_xer;
xer_type_encoder_f Temperaturec_encode_xer;
per_type_decoder_f Temperaturec_decode_uper;
per_type_encoder_f Temperaturec_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Temperaturec_H_ */
#include <asn_internal.h>
