/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#include "Timestamp.h"

static asn_TYPE_member_t asn_MBR_Timestamp_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Timestamp, timehours),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Timehours,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"timehours"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Timestamp, timeminutes),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Timeminutes,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"timeminutes"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Timestamp, timeseconds),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Timeseconds,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"timeseconds"
		},
};
static const ber_tlv_tag_t asn_DEF_Timestamp_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Timestamp_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 2 }, /* timehours */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 1 }, /* timeminutes */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -2, 0 } /* timeseconds */
};
static asn_SEQUENCE_specifics_t asn_SPC_Timestamp_specs_1 = {
	sizeof(struct Timestamp),
	offsetof(struct Timestamp, _asn_ctx),
	asn_MAP_Timestamp_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Timestamp = {
	"Timestamp",
	"Timestamp",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Timestamp_tags_1,
	sizeof(asn_DEF_Timestamp_tags_1)
		/sizeof(asn_DEF_Timestamp_tags_1[0]), /* 1 */
	asn_DEF_Timestamp_tags_1,	/* Same as above */
	sizeof(asn_DEF_Timestamp_tags_1)
		/sizeof(asn_DEF_Timestamp_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Timestamp_1,
	3,	/* Elements count */
	&asn_SPC_Timestamp_specs_1	/* Additional specs */
};

