/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Timeetaatfixnext_H_
#define	_Timeetaatfixnext_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASNTime.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Timeetaatfixnext */
typedef Time_t	 Timeetaatfixnext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Timeetaatfixnext;
asn_struct_free_f Timeetaatfixnext_free;
asn_struct_print_f Timeetaatfixnext_print;
asn_constr_check_f Timeetaatfixnext_constraint;
ber_type_decoder_f Timeetaatfixnext_decode_ber;
der_type_encoder_f Timeetaatfixnext_encode_der;
xer_type_decoder_f Timeetaatfixnext_decode_xer;
xer_type_encoder_f Timeetaatfixnext_encode_xer;
per_type_decoder_f Timeetaatfixnext_decode_uper;
per_type_encoder_f Timeetaatfixnext_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Timeetaatfixnext_H_ */
#include <asn_internal.h>
