/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Timedepartureedct_H_
#define	_Timedepartureedct_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASNTime.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Timedepartureedct */
typedef Time_t	 Timedepartureedct_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Timedepartureedct;
asn_struct_free_f Timedepartureedct_free;
asn_struct_print_f Timedepartureedct_print;
asn_constr_check_f Timedepartureedct_constraint;
ber_type_decoder_f Timedepartureedct_decode_ber;
der_type_encoder_f Timedepartureedct_encode_der;
xer_type_decoder_f Timedepartureedct_decode_xer;
xer_type_encoder_f Timedepartureedct_encode_xer;
per_type_decoder_f Timedepartureedct_decode_uper;
per_type_encoder_f Timedepartureedct_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Timedepartureedct_H_ */
#include <asn_internal.h>
