/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_TimeDistanceoffsetDirection_H_
#define	_TimeDistanceoffsetDirection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Time.h"
#include "Distanceoffset.h"
#include "Direction.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TimeDistanceoffsetDirection */
typedef struct TimeDistanceoffsetDirection {
	Time_t	 time;
	Distanceoffset_t	 distanceoffset;
	Direction_t	 direction;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TimeDistanceoffsetDirection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TimeDistanceoffsetDirection;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeDistanceoffsetDirection_H_ */
#include <asn_internal.h>
