/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM103TimeSpeedSpeed_H_
#define	_UM103TimeSpeedSpeed_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TimeSpeedSpeed.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM103TimeSpeedSpeed */
typedef TimeSpeedSpeed_t	 UM103TimeSpeedSpeed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM103TimeSpeedSpeed;
asn_struct_free_f UM103TimeSpeedSpeed_free;
asn_struct_print_f UM103TimeSpeedSpeed_print;
asn_constr_check_f UM103TimeSpeedSpeed_constraint;
ber_type_decoder_f UM103TimeSpeedSpeed_decode_ber;
der_type_encoder_f UM103TimeSpeedSpeed_encode_der;
xer_type_decoder_f UM103TimeSpeedSpeed_decode_xer;
xer_type_encoder_f UM103TimeSpeedSpeed_encode_xer;
per_type_decoder_f UM103TimeSpeedSpeed_decode_uper;
per_type_encoder_f UM103TimeSpeedSpeed_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM103TimeSpeedSpeed_H_ */
#include <asn_internal.h>
