/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM105AltitudeSpeedSpeed_H_
#define	_UM105AltitudeSpeedSpeed_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AltitudeSpeedSpeed.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM105AltitudeSpeedSpeed */
typedef AltitudeSpeedSpeed_t	 UM105AltitudeSpeedSpeed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM105AltitudeSpeedSpeed;
asn_struct_free_f UM105AltitudeSpeedSpeed_free;
asn_struct_print_f UM105AltitudeSpeedSpeed_print;
asn_constr_check_f UM105AltitudeSpeedSpeed_constraint;
ber_type_decoder_f UM105AltitudeSpeedSpeed_decode_ber;
der_type_encoder_f UM105AltitudeSpeedSpeed_encode_der;
xer_type_decoder_f UM105AltitudeSpeedSpeed_decode_xer;
xer_type_encoder_f UM105AltitudeSpeedSpeed_encode_xer;
per_type_decoder_f UM105AltitudeSpeedSpeed_decode_uper;
per_type_encoder_f UM105AltitudeSpeedSpeed_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM105AltitudeSpeedSpeed_H_ */
#include <asn_internal.h>
