/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM114Speed_H_
#define	_UM114Speed_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Speed.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM114Speed */
typedef Speed_t	 UM114Speed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM114Speed;
asn_struct_free_f UM114Speed_free;
asn_struct_print_f UM114Speed_print;
asn_constr_check_f UM114Speed_constraint;
ber_type_decoder_f UM114Speed_decode_ber;
der_type_encoder_f UM114Speed_encode_der;
xer_type_decoder_f UM114Speed_decode_xer;
xer_type_encoder_f UM114Speed_encode_xer;
per_type_decoder_f UM114Speed_decode_uper;
per_type_encoder_f UM114Speed_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM114Speed_H_ */
#include <asn_internal.h>
