/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM117ICAOunitnameFrequency_H_
#define	_UM117ICAOunitnameFrequency_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ICAOunitnameFrequency.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM117ICAOunitnameFrequency */
typedef ICAOunitnameFrequency_t	 UM117ICAOunitnameFrequency_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM117ICAOunitnameFrequency;
asn_struct_free_f UM117ICAOunitnameFrequency_free;
asn_struct_print_f UM117ICAOunitnameFrequency_print;
asn_constr_check_f UM117ICAOunitnameFrequency_constraint;
ber_type_decoder_f UM117ICAOunitnameFrequency_decode_ber;
der_type_encoder_f UM117ICAOunitnameFrequency_encode_der;
xer_type_decoder_f UM117ICAOunitnameFrequency_decode_xer;
xer_type_encoder_f UM117ICAOunitnameFrequency_encode_xer;
per_type_decoder_f UM117ICAOunitnameFrequency_decode_uper;
per_type_encoder_f UM117ICAOunitnameFrequency_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM117ICAOunitnameFrequency_H_ */
#include <asn_internal.h>
