/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM122TimeICAOunitnameFrequency_H_
#define	_UM122TimeICAOunitnameFrequency_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TimeICAOunitnameFrequency.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM122TimeICAOunitnameFrequency */
typedef TimeICAOunitnameFrequency_t	 UM122TimeICAOunitnameFrequency_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM122TimeICAOunitnameFrequency;
asn_struct_free_f UM122TimeICAOunitnameFrequency_free;
asn_struct_print_f UM122TimeICAOunitnameFrequency_print;
asn_constr_check_f UM122TimeICAOunitnameFrequency_constraint;
ber_type_decoder_f UM122TimeICAOunitnameFrequency_decode_ber;
der_type_encoder_f UM122TimeICAOunitnameFrequency_encode_der;
xer_type_decoder_f UM122TimeICAOunitnameFrequency_decode_xer;
xer_type_encoder_f UM122TimeICAOunitnameFrequency_encode_xer;
per_type_decoder_f UM122TimeICAOunitnameFrequency_decode_uper;
per_type_encoder_f UM122TimeICAOunitnameFrequency_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM122TimeICAOunitnameFrequency_H_ */
#include <asn_internal.h>
