/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM157Frequency_H_
#define	_UM157Frequency_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Frequency.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM157Frequency */
typedef Frequency_t	 UM157Frequency_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM157Frequency;
asn_struct_free_f UM157Frequency_free;
asn_struct_print_f UM157Frequency_print;
asn_constr_check_f UM157Frequency_constraint;
ber_type_decoder_f UM157Frequency_decode_ber;
der_type_encoder_f UM157Frequency_encode_der;
xer_type_decoder_f UM157Frequency_decode_xer;
xer_type_encoder_f UM157Frequency_encode_xer;
per_type_decoder_f UM157Frequency_decode_uper;
per_type_encoder_f UM157Frequency_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM157Frequency_H_ */
#include <asn_internal.h>
