/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM152DistanceoffsetDirection_H_
#define	_UM152DistanceoffsetDirection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DistanceoffsetDirection.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM152DistanceoffsetDirection */
typedef DistanceoffsetDirection_t	 UM152DistanceoffsetDirection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM152DistanceoffsetDirection;
asn_struct_free_f UM152DistanceoffsetDirection_free;
asn_struct_print_f UM152DistanceoffsetDirection_print;
asn_constr_check_f UM152DistanceoffsetDirection_constraint;
ber_type_decoder_f UM152DistanceoffsetDirection_decode_ber;
der_type_encoder_f UM152DistanceoffsetDirection_encode_der;
xer_type_decoder_f UM152DistanceoffsetDirection_decode_xer;
xer_type_encoder_f UM152DistanceoffsetDirection_encode_xer;
per_type_decoder_f UM152DistanceoffsetDirection_decode_uper;
per_type_encoder_f UM152DistanceoffsetDirection_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM152DistanceoffsetDirection_H_ */
#include <asn_internal.h>
