/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM150AltitudeTime_H_
#define	_UM150AltitudeTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AltitudeTime.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM150AltitudeTime */
typedef AltitudeTime_t	 UM150AltitudeTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM150AltitudeTime;
asn_struct_free_f UM150AltitudeTime_free;
asn_struct_print_f UM150AltitudeTime_print;
asn_constr_check_f UM150AltitudeTime_constraint;
ber_type_decoder_f UM150AltitudeTime_decode_ber;
der_type_encoder_f UM150AltitudeTime_encode_der;
xer_type_decoder_f UM150AltitudeTime_decode_xer;
xer_type_encoder_f UM150AltitudeTime_encode_xer;
per_type_decoder_f UM150AltitudeTime_decode_uper;
per_type_encoder_f UM150AltitudeTime_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM150AltitudeTime_H_ */
#include <asn_internal.h>
