/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM158Atiscode_H_
#define	_UM158Atiscode_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Atiscode.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM158Atiscode */
typedef Atiscode_t	 UM158Atiscode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM158Atiscode;
asn_struct_free_f UM158Atiscode_free;
asn_struct_print_f UM158Atiscode_print;
asn_constr_check_f UM158Atiscode_constraint;
ber_type_decoder_f UM158Atiscode_decode_ber;
der_type_encoder_f UM158Atiscode_encode_der;
xer_type_decoder_f UM158Atiscode_decode_xer;
xer_type_encoder_f UM158Atiscode_encode_xer;
per_type_decoder_f UM158Atiscode_decode_uper;
per_type_encoder_f UM158Atiscode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM158Atiscode_H_ */
#include <asn_internal.h>
