/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM163ICAOfacilitydesignationTp4table_H_
#define	_UM163ICAOfacilitydesignationTp4table_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ICAOfacilitydesignationTp4table.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM163ICAOfacilitydesignationTp4table */
typedef ICAOfacilitydesignationTp4table_t	 UM163ICAOfacilitydesignationTp4table_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM163ICAOfacilitydesignationTp4table;
asn_struct_free_f UM163ICAOfacilitydesignationTp4table_free;
asn_struct_print_f UM163ICAOfacilitydesignationTp4table_print;
asn_constr_check_f UM163ICAOfacilitydesignationTp4table_constraint;
ber_type_decoder_f UM163ICAOfacilitydesignationTp4table_decode_ber;
der_type_encoder_f UM163ICAOfacilitydesignationTp4table_encode_der;
xer_type_decoder_f UM163ICAOfacilitydesignationTp4table_decode_xer;
xer_type_encoder_f UM163ICAOfacilitydesignationTp4table_encode_xer;
per_type_decoder_f UM163ICAOfacilitydesignationTp4table_decode_uper;
per_type_encoder_f UM163ICAOfacilitydesignationTp4table_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM163ICAOfacilitydesignationTp4table_H_ */
#include <asn_internal.h>
