/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM173Verticalrate_H_
#define	_UM173Verticalrate_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Verticalrate.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM173Verticalrate */
typedef Verticalrate_t	 UM173Verticalrate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM173Verticalrate;
asn_struct_free_f UM173Verticalrate_free;
asn_struct_print_f UM173Verticalrate_print;
asn_constr_check_f UM173Verticalrate_constraint;
ber_type_decoder_f UM173Verticalrate_decode_ber;
der_type_encoder_f UM173Verticalrate_encode_der;
xer_type_decoder_f UM173Verticalrate_decode_xer;
xer_type_encoder_f UM173Verticalrate_encode_xer;
per_type_decoder_f UM173Verticalrate_decode_uper;
per_type_encoder_f UM173Verticalrate_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM173Verticalrate_H_ */
#include <asn_internal.h>
