/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM172Verticalrate_H_
#define	_UM172Verticalrate_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Verticalrate.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM172Verticalrate */
typedef Verticalrate_t	 UM172Verticalrate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM172Verticalrate;
asn_struct_free_f UM172Verticalrate_free;
asn_struct_print_f UM172Verticalrate_print;
asn_constr_check_f UM172Verticalrate_constraint;
ber_type_decoder_f UM172Verticalrate_decode_ber;
der_type_encoder_f UM172Verticalrate_encode_der;
xer_type_decoder_f UM172Verticalrate_decode_xer;
xer_type_encoder_f UM172Verticalrate_encode_xer;
per_type_decoder_f UM172Verticalrate_decode_uper;
per_type_encoder_f UM172Verticalrate_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM172Verticalrate_H_ */
#include <asn_internal.h>
