/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM178NULL_H_
#define	_UM178NULL_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UM178NULL */
typedef NULL_t	 UM178NULL_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM178NULL;
asn_struct_free_f UM178NULL_free;
asn_struct_print_f UM178NULL_print;
asn_constr_check_f UM178NULL_constraint;
ber_type_decoder_f UM178NULL_decode_ber;
der_type_encoder_f UM178NULL_encode_der;
xer_type_decoder_f UM178NULL_decode_xer;
xer_type_encoder_f UM178NULL_encode_xer;
per_type_decoder_f UM178NULL_decode_uper;
per_type_encoder_f UM178NULL_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM178NULL_H_ */
#include <asn_internal.h>
