/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM28AltitudeTime_H_
#define	_UM28AltitudeTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AltitudeTime.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM28AltitudeTime */
typedef AltitudeTime_t	 UM28AltitudeTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM28AltitudeTime;
asn_struct_free_f UM28AltitudeTime_free;
asn_struct_print_f UM28AltitudeTime_print;
asn_constr_check_f UM28AltitudeTime_constraint;
ber_type_decoder_f UM28AltitudeTime_decode_ber;
der_type_encoder_f UM28AltitudeTime_encode_der;
xer_type_decoder_f UM28AltitudeTime_decode_xer;
xer_type_encoder_f UM28AltitudeTime_encode_xer;
per_type_decoder_f UM28AltitudeTime_decode_uper;
per_type_encoder_f UM28AltitudeTime_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM28AltitudeTime_H_ */
#include <asn_internal.h>
