/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM41Altitude_H_
#define	_UM41Altitude_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Altitude.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM41Altitude */
typedef Altitude_t	 UM41Altitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM41Altitude;
asn_struct_free_f UM41Altitude_free;
asn_struct_print_f UM41Altitude_print;
asn_constr_check_f UM41Altitude_constraint;
ber_type_decoder_f UM41Altitude_decode_ber;
der_type_encoder_f UM41Altitude_encode_der;
xer_type_decoder_f UM41Altitude_decode_xer;
xer_type_encoder_f UM41Altitude_encode_xer;
per_type_decoder_f UM41Altitude_decode_uper;
per_type_encoder_f UM41Altitude_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM41Altitude_H_ */
#include <asn_internal.h>
