/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM46PositionAltitude_H_
#define	_UM46PositionAltitude_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PositionAltitude.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM46PositionAltitude */
typedef PositionAltitude_t	 UM46PositionAltitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM46PositionAltitude;
asn_struct_free_f UM46PositionAltitude_free;
asn_struct_print_f UM46PositionAltitude_print;
asn_constr_check_f UM46PositionAltitude_constraint;
ber_type_decoder_f UM46PositionAltitude_decode_ber;
der_type_encoder_f UM46PositionAltitude_encode_der;
xer_type_decoder_f UM46PositionAltitude_decode_xer;
xer_type_encoder_f UM46PositionAltitude_encode_xer;
per_type_decoder_f UM46PositionAltitude_decode_uper;
per_type_encoder_f UM46PositionAltitude_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM46PositionAltitude_H_ */
#include <asn_internal.h>
