/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM50PositionAltitudeAltitude_H_
#define	_UM50PositionAltitudeAltitude_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PositionAltitudeAltitude.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM50PositionAltitudeAltitude */
typedef PositionAltitudeAltitude_t	 UM50PositionAltitudeAltitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM50PositionAltitudeAltitude;
asn_struct_free_f UM50PositionAltitudeAltitude_free;
asn_struct_print_f UM50PositionAltitudeAltitude_print;
asn_constr_check_f UM50PositionAltitudeAltitude_constraint;
ber_type_decoder_f UM50PositionAltitudeAltitude_decode_ber;
der_type_encoder_f UM50PositionAltitudeAltitude_encode_der;
xer_type_decoder_f UM50PositionAltitudeAltitude_decode_xer;
xer_type_encoder_f UM50PositionAltitudeAltitude_encode_xer;
per_type_decoder_f UM50PositionAltitudeAltitude_decode_uper;
per_type_encoder_f UM50PositionAltitudeAltitude_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM50PositionAltitudeAltitude_H_ */
#include <asn_internal.h>
