/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM57PositionSpeed_H_
#define	_UM57PositionSpeed_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PositionSpeed.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM57PositionSpeed */
typedef PositionSpeed_t	 UM57PositionSpeed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM57PositionSpeed;
asn_struct_free_f UM57PositionSpeed_free;
asn_struct_print_f UM57PositionSpeed_print;
asn_constr_check_f UM57PositionSpeed_constraint;
ber_type_decoder_f UM57PositionSpeed_decode_ber;
der_type_encoder_f UM57PositionSpeed_encode_der;
xer_type_decoder_f UM57PositionSpeed_decode_xer;
xer_type_encoder_f UM57PositionSpeed_encode_xer;
per_type_decoder_f UM57PositionSpeed_decode_uper;
per_type_encoder_f UM57PositionSpeed_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM57PositionSpeed_H_ */
#include <asn_internal.h>
