/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM63TimePositionAltitudeSpeed_H_
#define	_UM63TimePositionAltitudeSpeed_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TimePositionAltitudeSpeed.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM63TimePositionAltitudeSpeed */
typedef TimePositionAltitudeSpeed_t	 UM63TimePositionAltitudeSpeed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM63TimePositionAltitudeSpeed;
asn_struct_free_f UM63TimePositionAltitudeSpeed_free;
asn_struct_print_f UM63TimePositionAltitudeSpeed_print;
asn_constr_check_f UM63TimePositionAltitudeSpeed_constraint;
ber_type_decoder_f UM63TimePositionAltitudeSpeed_decode_ber;
der_type_encoder_f UM63TimePositionAltitudeSpeed_encode_der;
xer_type_decoder_f UM63TimePositionAltitudeSpeed_decode_xer;
xer_type_encoder_f UM63TimePositionAltitudeSpeed_encode_xer;
per_type_decoder_f UM63TimePositionAltitudeSpeed_decode_uper;
per_type_encoder_f UM63TimePositionAltitudeSpeed_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM63TimePositionAltitudeSpeed_H_ */
#include <asn_internal.h>
