/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM66TimeDistanceoffsetDirection_H_
#define	_UM66TimeDistanceoffsetDirection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TimeDistanceoffsetDirection.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM66TimeDistanceoffsetDirection */
typedef TimeDistanceoffsetDirection_t	 UM66TimeDistanceoffsetDirection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM66TimeDistanceoffsetDirection;
asn_struct_free_f UM66TimeDistanceoffsetDirection_free;
asn_struct_print_f UM66TimeDistanceoffsetDirection_print;
asn_constr_check_f UM66TimeDistanceoffsetDirection_constraint;
ber_type_decoder_f UM66TimeDistanceoffsetDirection_decode_ber;
der_type_encoder_f UM66TimeDistanceoffsetDirection_encode_der;
xer_type_decoder_f UM66TimeDistanceoffsetDirection_decode_xer;
xer_type_encoder_f UM66TimeDistanceoffsetDirection_encode_xer;
per_type_decoder_f UM66TimeDistanceoffsetDirection_decode_uper;
per_type_encoder_f UM66TimeDistanceoffsetDirection_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM66TimeDistanceoffsetDirection_H_ */
#include <asn_internal.h>
