/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM73Predepartureclearance_H_
#define	_UM73Predepartureclearance_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Predepartureclearance.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM73Predepartureclearance */
typedef Predepartureclearance_t	 UM73Predepartureclearance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM73Predepartureclearance;
asn_struct_free_f UM73Predepartureclearance_free;
asn_struct_print_f UM73Predepartureclearance_print;
asn_constr_check_f UM73Predepartureclearance_constraint;
ber_type_decoder_f UM73Predepartureclearance_decode_ber;
der_type_encoder_f UM73Predepartureclearance_encode_der;
xer_type_decoder_f UM73Predepartureclearance_decode_xer;
xer_type_encoder_f UM73Predepartureclearance_encode_xer;
per_type_decoder_f UM73Predepartureclearance_decode_uper;
per_type_encoder_f UM73Predepartureclearance_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM73Predepartureclearance_H_ */
#include <asn_internal.h>
