/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM78AltitudePosition_H_
#define	_UM78AltitudePosition_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AltitudePosition.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM78AltitudePosition */
typedef AltitudePosition_t	 UM78AltitudePosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM78AltitudePosition;
asn_struct_free_f UM78AltitudePosition_free;
asn_struct_print_f UM78AltitudePosition_print;
asn_constr_check_f UM78AltitudePosition_constraint;
ber_type_decoder_f UM78AltitudePosition_decode_ber;
der_type_encoder_f UM78AltitudePosition_encode_der;
xer_type_decoder_f UM78AltitudePosition_decode_xer;
xer_type_encoder_f UM78AltitudePosition_encode_xer;
per_type_decoder_f UM78AltitudePosition_decode_uper;
per_type_encoder_f UM78AltitudePosition_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM78AltitudePosition_H_ */
#include <asn_internal.h>
