/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM84PositionProcedurename_H_
#define	_UM84PositionProcedurename_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PositionProcedurename.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM84PositionProcedurename */
typedef PositionProcedurename_t	 UM84PositionProcedurename_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM84PositionProcedurename;
asn_struct_free_f UM84PositionProcedurename_free;
asn_struct_print_f UM84PositionProcedurename_print;
asn_constr_check_f UM84PositionProcedurename_constraint;
ber_type_decoder_f UM84PositionProcedurename_decode_ber;
der_type_encoder_f UM84PositionProcedurename_encode_der;
xer_type_decoder_f UM84PositionProcedurename_decode_xer;
xer_type_encoder_f UM84PositionProcedurename_encode_xer;
per_type_decoder_f UM84PositionProcedurename_decode_uper;
per_type_encoder_f UM84PositionProcedurename_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM84PositionProcedurename_H_ */
#include <asn_internal.h>
