/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM86PositionRouteclearance_H_
#define	_UM86PositionRouteclearance_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PositionRouteclearance.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM86PositionRouteclearance */
typedef PositionRouteclearance_t	 UM86PositionRouteclearance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM86PositionRouteclearance;
asn_struct_free_f UM86PositionRouteclearance_free;
asn_struct_print_f UM86PositionRouteclearance_print;
asn_constr_check_f UM86PositionRouteclearance_constraint;
ber_type_decoder_f UM86PositionRouteclearance_decode_ber;
der_type_encoder_f UM86PositionRouteclearance_encode_der;
xer_type_decoder_f UM86PositionRouteclearance_decode_xer;
xer_type_encoder_f UM86PositionRouteclearance_encode_xer;
per_type_decoder_f UM86PositionRouteclearance_decode_uper;
per_type_encoder_f UM86PositionRouteclearance_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM86PositionRouteclearance_H_ */
#include <asn_internal.h>
