/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM89TimePosition_H_
#define	_UM89TimePosition_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TimePosition.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM89TimePosition */
typedef TimePosition_t	 UM89TimePosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM89TimePosition;
asn_struct_free_f UM89TimePosition_free;
asn_struct_print_f UM89TimePosition_print;
asn_constr_check_f UM89TimePosition_constraint;
ber_type_decoder_f UM89TimePosition_decode_ber;
der_type_encoder_f UM89TimePosition_encode_der;
xer_type_decoder_f UM89TimePosition_decode_xer;
xer_type_encoder_f UM89TimePosition_encode_xer;
per_type_decoder_f UM89TimePosition_decode_uper;
per_type_encoder_f UM89TimePosition_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM89TimePosition_H_ */
#include <asn_internal.h>
