/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM94DirectionDegrees_H_
#define	_UM94DirectionDegrees_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DirectionDegrees.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM94DirectionDegrees */
typedef DirectionDegrees_t	 UM94DirectionDegrees_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM94DirectionDegrees;
asn_struct_free_f UM94DirectionDegrees_free;
asn_struct_print_f UM94DirectionDegrees_print;
asn_constr_check_f UM94DirectionDegrees_constraint;
ber_type_decoder_f UM94DirectionDegrees_decode_ber;
der_type_encoder_f UM94DirectionDegrees_encode_der;
xer_type_decoder_f UM94DirectionDegrees_decode_xer;
xer_type_encoder_f UM94DirectionDegrees_encode_xer;
per_type_decoder_f UM94DirectionDegrees_decode_uper;
per_type_encoder_f UM94DirectionDegrees_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM94DirectionDegrees_H_ */
#include <asn_internal.h>
