/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_UM97PositionDegrees_H_
#define	_UM97PositionDegrees_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PositionDegrees.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UM97PositionDegrees */
typedef PositionDegrees_t	 UM97PositionDegrees_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM97PositionDegrees;
asn_struct_free_f UM97PositionDegrees_free;
asn_struct_print_f UM97PositionDegrees_print;
asn_constr_check_f UM97PositionDegrees_constraint;
ber_type_decoder_f UM97PositionDegrees_decode_ber;
der_type_encoder_f UM97PositionDegrees_encode_der;
xer_type_decoder_f UM97PositionDegrees_decode_xer;
xer_type_encoder_f UM97PositionDegrees_encode_xer;
per_type_decoder_f UM97PositionDegrees_decode_uper;
per_type_encoder_f UM97PositionDegrees_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UM97PositionDegrees_H_ */
#include <asn_internal.h>
