/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Verticaldirection_H_
#define	_Verticaldirection_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Verticaldirection {
	Verticaldirection_up	= 0,
	Verticaldirection_down	= 1
} e_Verticaldirection;

/* Verticaldirection */
typedef long	 Verticaldirection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Verticaldirection;
asn_struct_free_f Verticaldirection_free;
asn_struct_print_f Verticaldirection_print;
asn_constr_check_f Verticaldirection_constraint;
ber_type_decoder_f Verticaldirection_decode_ber;
der_type_encoder_f Verticaldirection_encode_der;
xer_type_decoder_f Verticaldirection_decode_xer;
xer_type_encoder_f Verticaldirection_encode_xer;
per_type_decoder_f Verticaldirection_decode_uper;
per_type_encoder_f Verticaldirection_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Verticaldirection_H_ */
#include <asn_internal.h>
