/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ATCTwoWayDataLinkCommunications"
 * 	found in "struct.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_Windspeed_H_
#define	_Windspeed_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Windspeedenglish.h"
#include "Windspeedmetric.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Windspeed_PR {
	Windspeed_PR_NOTHING,	/* No components present */
	Windspeed_PR_windspeedenglish,
	Windspeed_PR_windspeedmetric
} Windspeed_PR;

/* Windspeed */
typedef struct Windspeed {
	Windspeed_PR present;
	union Windspeed_u {
		Windspeedenglish_t	 windspeedenglish;
		Windspeedmetric_t	 windspeedmetric;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Windspeed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Windspeed;

#ifdef __cplusplus
}
#endif

#endif	/* _Windspeed_H_ */
#include <asn_internal.h>
